
#+BEGIN_EXPORT LaTeX
\title[Ice sheet mass flows]{Ice sheet mass flows}

\author[Mankoff and others]
{Kenneth D. MANKOFF$^{1,2}$,
Chad A. GREENE$^{3}$,
Benjamin DAVISON$^{4}$,
Alex S. GARDNER$^{3}$,
Désirée TREICHLER$^{5}$,
Will KOCHTITZKY$^{6}$,
Brice VAN LIEFFERINGE$^{7}$,
Genyu WANG$^{8}$
Chang-Qing KE$^{8}$,
Xavier FETTWEIS$^{9}$,
Thorben DÖHNE$^{10}$,
Robert FAUSTO$^{11}$,
Damien RINGEISEN$^{1,12,13}$}

\affiliation{%
$^1$NASA Goddard Institute for Space Studies, New York, NY, USA\\
$^2$Autonomic Integra LLC, New York, NY, USA\\
$^3$Jet Propulsion Laboratory California Institute of Technology Pasadena, CA, USA\\
$^4$School of Geography and Planning, University of Sheffield, Sheffield, UK\\
$^5$Department of Geography, University of Oslo, Oslo, Norway\\
$^6$University of New England, Biddeford, Maine, USA\\
$^7$Laboratoire de Glaciologie, Université libre de Bruxelles (ULB), Brussels, Belgium\\
$^8$Nanjing University, Nanjing, Jiangsu, China\\
$^9$SPHERES research units, Geography Department, University of Liège, Liège, Belgium\\
$^{10}$TUD Dresden University of Technology, Dresden, Germany\\
$^{11}$Geological Survey of Denmark and Greenland, Copenhagen, Denmark\\
$^{12}$Center for Climate Systems Research, Columbia University, New York, NY, USA\\
$^{13}$Now at: Canadian Centre for Climate Modelling and Analysis, Environment and Climate Change Canada (ECCC), Victoria, British Columbia, Canada.\\
Correspondence: Ken Mankoff
\email{ken.mankoff@nasa.gov}}
#+END_EXPORT

:settings_drawer:
#+Latex_Class: igs
#+AUTHOR: 
#+DATE: 
#+LaTeX_CLASS_OPTIONS: [jog,oneside,review]
# #+LaTeX_CLASS_OPTIONS: [jog,oneside]
#+Options: toc:nil ^:t {}:t title:nil

#+EXPORT_FILE_NAME: ms.tex

#+EXCLUDE_TAGS: noexport

#+LATEX_HEADER_EXTRA: \usepackage[utf8]{inputenc}
#+LATEX_HEADER_EXTRA: \usepackage{mathabx}
#+LATEX_HEADER_EXTRA: \usepackage{graphicx}
#+LATEX_HEADER_EXTRA: \usepackage{siunitx}
#+LATEX_HEADER_EXTRA: % \setcounter{secnumdepth}{2}

#+LATEX_HEADER_EXTRA: \jourvolume{V}
#+LATEX_HEADER_EXTRA: \jourissue{N}
#+LATEX_HEADER_EXTRA: \jourpubyear{YYYY}

#+PROPERTY: header-args:jupyter-python+ :dir (file-name-directory buffer-file-name) :session sankey
:end:

#+LATEX: \begin{frontmatter}
#+LATEX: \maketitle

# Author list: https://drive.google.com/drive/folders/1g9vXuQofIL5MgtrtQ2zzlLiu69j1kTvJ?usp=sharing
# Please add ORCID and Affiliation to CRediT file there.

#+LATEX: \begin{abstract}

Ice sheet mass loss is typically provided for grounded ice, because changes in floating ice are more difficult to measure and contribute minimally to sea level rise. However, net freshwater mass flow rate across ice sheet boundaries, including floating ice, is a better metric of ice sheet health.

Here we present total mass flows across ice sheet boundaries for both the Greenlandic and Antarctic ice sheets and their peripheral glaciers from 2010 through 2019. In addition to total mass flow, we provide constituent terms and gross rather than net values, including components that combine to provide surface mass balance (SMB).

Ice mass loss in Greenland is 330 \pm50 Gt yr^{-1} which is ~30 % larger than the 255 \pm40 Gt yr^{-1} grounded ice mass loss estimates that neglect floating ice changes. Ice mass loss in Antarctica is 450 \pm270 Gt yr^{-1} which is ~2.4x the 190 \pm115 Gt yr^{-1} grounded ice mass loss estimates. Freshwater mass flow rate from Greenland is ~1065 \pm120 Gt yr^{-1} or ~3x mass loss (~4x grounded mass loss), and from Antarctica is ~3110 \pm1515 Gt yr^{-1}, or ~7x mass loss (~16x grounded mass loss).

#+LATEX: \end{abstract}
#+LATEX: \end{frontmatter}


* Introduction and Background

Changes in ice sheet mass directly impacts sea-level change, so Greenland and Antarctica's net mass balance have been the focus of a great deal of recent scientific research (citet:ipcc_AR6_ch9,otosaka_2023,mankoff_2021,rignot_2019, and many others). The mass loss from the grounded portion of the Greenlandic and Antarctic ice sheets contributes to sea level rise (SLR), and can be captured by a single value or time series per ice sheet. Reporting a single value or time series derived from multiple years of data is beneficial because it simplifies interpretation and comparison. However, ice sheets are complex systems, and while their contribution to sea level rise is important, focusing on their SLR contribution alone provides minimal understanding of the processes at play, and how they change. As one example, an ice sheet that increases output via discharge but has that offset by an equal increase in inputs (e.g., snowfall) would report a neutral mass balance and no change in contribution to SLR, but has entered a different state when viewing constituent terms. Few studies consider all mass transport pathways and their relative magnitudes and uncertainties - this is typically limited to review papers, which may not focus on quantitative assessment of each process.

Studies that assess mass balance typically use one or a combination of three methods.

The gravimetric mass balance (GMB) method directly measures changes in the gravitational field generated by the ice sheets. It is observation-based and excels at measuring the grounded ice contribution to sea level rise, but cannot observe changes in floating ice as these do not cause changes in the gravitational field, nor distinguish processes that contribute to changes of the grounded ice. Spatial resolution is \sim100 km and temporal resolution is monthly (e.g., citet:groh_2019,dohne_2023).

The volumetric method estimates the total volume and change in volume of the ice sheets from altimetry. This method is also observation-based, has spatial resolution of \sim1000 m and temporal resolution is monthly (c.f citet:khan_2022_alt,simonsen_2021). It can be used over floating ice, and this is the primary method for observing ice shelf thinning from which ice shelf basal melt is inferred (e.g., citet:greene_2022,davison_2023). However, the volumetric method cannot be used to distinguish between surface and grounded basal processes and only reports total thinning \citep[c.f.,][]{karlsson_2021}.

Finally, the input-output (IO) method is a hybrid of regional climate models (RCM) and observations (flow velocity, ice thickness; e.g., citet:rignot_2019,gardner_2018,mouginot_2019,mankoff_2021). This method estimates inputs (e.g., snowfall) and outputs (e.g., surface melt and iceberg calving), and is typically reported at the low spatial resolution of individual glacier basins. Temporal resolution is ~10 days or whenever a new velocity map is generated, but given the  stability of the ice flow compared to the daily variability the SMB, the IO method can provide some estimate of daily mass balance citep:mankoff_2021. The IO method is the only one that captures all of the processes contributing to changes of grounded ice and provides gross values and constituent terms.

Here we use a combination of the IO method over grounded ice, the altimetry method over ice shelves, and other individual remote sensing estimates of ice shelf and glacier front advance and retreat. We provide results both in tabular form, and using Sankey diagrams that provide a visual method to compare magnitude of all processes within and between ice sheets, and flows representing relations between processes.

** Introduction to Sankey diagrams

Sankey diagrams are graphical representations of flow or movement of any property (e.g., mass, energy, money, etc.). An early and famous use was Charles Minard's Map of Napoleon's Russian Campaign of 1812 (c.f., citet:kraak_2021) that combines the magnitude of active soldiers overlaid on a geographical map. The method was later refined, popularized, and eventually named after Captain Matthew Henry Phineas Riall Sankey who used it to show, among other things, the energy efficiency of a steam engine.

A similar display to the diagrams presented here by \citet[][Figure 2]{cogley_2011} shows glacier processes overlaid on a glacier schematic and we build on that work by adding magnitude of processes and making the graphics proportional to magnitudes.

Appendix A has details on the software used to generate these Sankey diagrams.

*** Interpreting these Sankey diagrams

Sankey diagrams are generally intuitive, but the following section may still be helpful in interpreting the diagrams shown here.

The widths of all lines are all proportional to each other both within and among Figures \ref{fig:gl}, \ref{fig:aq}, and \ref{fig:aq_regions} (Appendix B) but not Fig. \ref{fig:aq_complex} (Appendix C).

Sankey diagrams balance all inputs and outputs, which introduces a complication for the use case here due to the mass imbalance. Traditionally, when a Sankey diagram has a loss term, it is an output. For example, all engines have energy inputs greater than outputs, the ratio between the two is a measure of efficiency, and the energy lost between input and output is displayed as an additional output.

In the Sankey diagrams here with net mass loss (drawdown or retreat), outputs are greater than inputs, so mass loss must then be a balancing input representing drawdown of the historical ice mass or retreat of the ice sheet boundary. In the Sankey diagrams with net mass gain (build-up or expansion), inputs are larger than outputs, so mass gain is a balancing output representing ice build-up or boundary expansion. We show these terms by truncating the input (mass loss) or output (mass gain) arrows in Figs. \ref{fig:gl} and \ref{fig:aq}.

Finally, the Sankey diagrams shown here are simplistic representations of mass flow across the three ice sheet boundaries (atmospheric, subglacial, and oceanic). We combine all inputs and outputs, not distinguishing between inputs over grounded ice vs. inputs over ice shelves, or other display options. However, alternate displays are possible, and a more complex display is shown in Appendix C which separates inputs and outputs by region (grounded, floating) in Antarctica.

* Terminology

We use the common terms from citet:cogley_2011 with a few clarifying points. We refer readers to Fig. 2 of citet:cogley_2011 for a graphical schematic showing mass flow pathways overlaid on a glacier including phases (solid, liquid, gas), and boundaries (grounded, floating, ocean).
 
Our estimates of mass flow include all ice in Greenland and Antarctica, including peripheral glaciers.

We use `grounding line' to refer to the ice/ocean/bed interface underneath ice shelves and floating ice tongues. When there is no ice shelf, we use the term `front' as in `calving front' or `frontal advance'.

Sublimation from surface mass balance is often a net term that includes condensation (gas -> liquid) , deposition (gas -> solid), evaporation (liquid -> gas), and  sublimation (solid -> gas). Here, we distinguish between all unique four types of phase transitions. Runoff is meltwater or rain that does not refreeze and instead leaves the ice sheet.

This work does not explicitly report submarine melt, the sum of all melt that occurs underwater, but instead we use and report constituent terms when available. Frontal melt is from vertical faces at the calving edge of Greenlandic glaciers. There are no estimates of frontal melt at the calving edge of Antarctic ice shelves or non-shelf calving regions, but mass flow across this boundary is then included in the calving estimates. Ice shelf basal melt is from horizontal surfaces under ice shelves in Greenland and Antarctica. 

We do not use the term `basal melt' because it does not distinguish between grounded or floating ice. Instead we use `ice shelf basal melt' and `grounded ice basal melt'.

We generally avoid the term `flux' which by definition is per unit area. Because we do not report results per unit area, we use `mass flow rate' [Gt yr^{-1}].

Not all processes are directly observable due to limitations in measurements, nor are they all modeled. We are limited by the data provided in the products that we ingest to this work. We therefore sometimes report process and sometimes product. In many cases products and process are the same (e.g., `snowfall' process and the `snowfall' data product from the RCM). An example where product rather than process is presented is the `frontal retreat' data product which is a combination of the calving and frontal melting processes. An example where processes rather than product is presented is the Greenland ice discharge product which is not shown because discharge is measured a few km upstream of the grounding line. Instead, we show the downstream calving and frontal melt processes.


* Tables                                                  :ignore:

# Evaluate then cut-and-paste table lines into LaTeX table below.

** Greenland                                              :ignore:

#+BEGIN_SRC jupyter-python :exports none :var tbl=README.org:gl_baseline :colnames no :results output
import numpy as np
import pandas as pd

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.set_index('Term')

for i,v in zip(df.index,df['Value']):
    df.loc[i,'Value'] = eval(v)
df['Value'] = df['Value'].astype(int)

for i,v in zip(df.index,df['Source']):
    if v == '': continue
    df.loc[i,'Source'] = "\\citet{" + v + "}"

# df = df.replace(to_replace='0', value=' ')
df.loc['Grounding line retreat', 'Source'] = "See methods"
df.loc['Discharge', 'Source'] = "See methods"

print(df.to_latex())
#+END_SRC

#+BEGIN_latex
\begin{table*}[htbp]
\caption{Greenland mass flow terms, values [Gt yr\textsuperscript{-1}], uncertainty (Unc.) [\%], and metadata. IO encodes input (I) or output (O) to or from grounded ice (subscript g) or ocean (subscript o). The 15 \% uncertainty reported for the SMB components (top eight rows) is from net SMB, not the individual components.}
\label{tab:gl}
\centering
\begin{tabular}{lrrccl}
Term & Value & Unc. & IO & Period & Source\\
\hline
Rainfall & 40 & 15 & I_g & 2010-2019 & \citet{fettweis_2020} \\
Condensation & 5 & 15 & I_g & 2010-2019 & \citet{fettweis_2020} \\
Deposition & 10 & 15 & I_g & 2010-2019 & \citet{fettweis_2020} \\
Snowfall & 680 & 15 & I_g & 2010-2019 & \citet{fettweis_2020} \\
Evaporation & 5 & 15 & O_g & 2010-2019 & \citet{fettweis_2020} \\
Runoff & 435 & 15 & O_g & 2010-2019 & \citet{fettweis_2020} \\
Sublimation & 60 & 15 & O_g & 2010-2019 & \citet{fettweis_2020} \\
Refreezing & 200 & 15 &  & 2010-2019 & \citet{fettweis_2020} \\
Grounded ice basal melt & 20 & 20 & O_g & steady & \citet{karlsson_2021} \\
Discharge & 470 & 10 &  & 2010-2019 & See methods \\
Calving & 235 & 30 & O_o &  & \citet{rignot_2010} \\
Frontal melt & 235 & 30 & O_o &  & \citet{rignot_2010} \\
Ice shelf basal melt & 25 & 40 & O_o & 2013-2022 & \citet{wang_2024} \\
Ice shelf basal freeze-on & 5 & 40 & I_o & 2013-2022 & \citet{wang_2024} \\
Grounding line retreat & 5 & ? & O_g &  & See methods \\
Grounding line advance & 0 & ? & I_g &  & See methods \\
Frontal retreat & 50 & 5 & O_o & 2010-2020 & \citet{kochtitzky_2023} \\
Frontal advance & 0 &  & I_o & 2010-2020 & \citet{kochtitzky_2023} \\
\end{tabular}
\end{table*}
#+END_latex


** Antarctica                                             :ignore:

#+BEGIN_SRC jupyter-python :exports none :var tbl=README.org:aq :colnames no 
import numpy as np
import pandas as pd

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.set_index('Term')

for i,v in zip(df.index,df['Source']):
    if v == '': continue
    df.loc[i,'Source'] = "\\citet{" + v + "}"

def crep(s):
    if "_" in s: return s[0] + '_' + s[-1]
    return s
df.columns = [crep(_) for _ in df.columns]

df = df.replace(to_replace='0', value=' ')

df.loc['Discharge', 'Source'] = "See caption (a)"
df.loc['Calving', 'Source'] = "See caption (b)"
df.loc['Grounding line retreat', 'Source'] = "See methods"

print(df.to_latex())
# df
#+END_SRC

#+BEGIN_latex
\begin{table*}[htbp]
\caption{Antarctic mass flow terms. E, W, and P represent East, West, and Peninsula regions respectively. Subscripts g and s represent grounded and shelf components respectively. IO encodes if the Term is an input (I) or an output (O). Values are in units Gt yr\textsuperscript{-1} except Unc. (uncertainty) which is \%. Values are rounded to nearest integer except values < 0.5 are rounded up to 1. (a) Discharge is grounded ice discharge to ice shelves from \citet{davison_2023} plus grounded ice discharge from non-shelf coastal regions and from islands from \citet{rignot_2019}. (b) Calving is ice shelf terminus calving from \citet{greene_2022} plus grounded ice calving from non-shelf coastal regions and from islands from \citet{rignot_2019}. The 15 \% uncertainty reported for the SMB components (top eight rows) is from net SMB, not the individual components.}
\label{tab:aq}
\centering
\begin{tabular}{lrrrrrrrccl}
Term & E_g & W_g & P_g & E_s & W_s & P_s & Unc. & IO & Period & Source \\
\hline
Rainfall & 1 & 1 & 2 & 1 & 1 & 2 & 15 & I & 2010-2019 & \citet{kittel_2021} \\
Condensation & 1 & 1 & 1 & 1 & 1 & 1 & 15 & I & 2010-2019 & \citet{kittel_2021} \\
Deposition & 37 & 24 & 6 & 6 & 6 & 2 & 15 & I & 2010-2019 & \citet{kittel_2021} \\
Snowfall & 1392 & 724 & 282 & 172 & 180 & 57 & 15 & I & 2010-2019 & \citet{kittel_2021} \\
Refreezing & 15 & 5 & 19 & 26 & 10 & 32 & 15 &  & 2010-2019 & \citet{kittel_2021} \\
Evaporation & 1 & 1 & 1 & 1 & 1 & 1 & 15 & O & 2010-2019 & \citet{kittel_2021} \\
Runoff & 1 & 1 & 2 & 2 & 1 & 4 & 15 & O & 2010-2019 & \citet{kittel_2021} \\
Sublimation & 151 & 33 & 13 & 23 & 9 & 4 & 15 & O & 2010-2019 & \citet{kittel_2021} \\
Grounded ice basal melt & 47 & 19 & 3 &   &   &   & 30 & O &  & \citet{van-liefferinge_2013} \\
Discharge & 1147 & 902 & 292 &   &   &   & 5 -- 50 &  & 2008-2019 & See caption (a) \\
Calving & 223 & 46 & 139 & 694 & 567 & 104 & 5 & O & 2010-2019 & See caption (b) \\
Frontal melt &   &   &   &   &   &   &  & O &  &  \\
Ice shelf basal melt &   &   &   & 527 & 684 & 164 & 150 & O & 2010-2017 & \citet{paolo_2023} \\
Ice shelf basal freeze-on &   &   &   & 208 & 147 & 11 & 300 & I & 2010-2017 & \citet{paolo_2023} \\
Grounding line retreat & 1 & 45 & 1 &   &   &   & 15 & O & 1997-2021 & See methods\\
Grounding line advance &   &   &   &   &   &   &  & I & 1997-2021 & See methods\\
Frontal retreat &   &   &   & 69 & 206 & 125 & 5 & O & 2010-2021 & \citet{greene_2022} \\
Frontal advance &   &   &   & 192 & 2 & 1 & 5 & I & 2010-2021 & \citet{greene_2022} \\
\bottomrule
\end{tabular}
\end{table*}
#+END_latex



* Methods

The full methods (source code) for this manuscript can be found at
https://doi.org/10.5281/zenodo.15819650 which archives and assigns a DOI to releases made from the source code repository at https://github.com/mankoff/sankey.

Below we detail the source of each mass flow term. We begin with the outputs as these are generally of broader interest, followed by the inputs. We then describe how net mass loss or gain are computed, and how uncertainty is estimated. Finally, we address other methods such as regional separation, temporal alignment, and rounding.

** Outputs

*** Sublimation, evaporation, and runoff

We use constituent terms (i.e., gross, not net) of surface mass balance from the Modèle Atmosphérique Régional (MAR) RCM for both Greenland citep:fettweis_2020 and Antarctica citep:kittel_2021.

*** Calving, frontal melt, and ice shelf basal melt

In Greenland, we use ice discharge across flux gates ~5 km upstream from the grounding lines citep:mankoff_2021. That discharge term at the flux gates is known to overestimate discharge across the downstream grounding line because it neglects SMB losses between the flux gate and grounding line. These losses are estimated at ~17 Gt yr^{-1} by citet:kochtitzky_2023 who uses flux gates closer to the grounding line than the citet:mankoff_2020_solid flux gates. The elevation of flux gates used by citet:mankoff_2020_solid were typically located tens to hundreds of meters higher (and therefore further from the calving front) than the flux gates used by citet:kochtitzky_2023. We estimate an average of ~3 Gt yr^{-1} are lost to surface melt while the ice transits this region. When estimating discharge from the perimeter of the ice sheet, we therefore subtract 20 Gt/yr from the more inland observations by citet:mankoff_2020_solid meaning frontal melt and calving are each reduced by 10 Gt yr^{-1} (see below for discharge split to frontal melt and calving). Peripheral glaciers are not included in the citet:mankoff_2020_solid product, but are added through estimates from citet:bollen_2023.

Greenlandic discharge from the flux gates is split into either calving or frontal melt at the calving front, which is the grounding line if no ice shelf is present, or shelf front if an ice shelf is present. This split is highly uncertain and minimally studied, but citet:rignot_2010 estimate that 20 - 80 % of the summer ice-front is directly melted by the ocean for the three glaciers they studied. From this, we split the discharge 50 \pm30 % between calving and frontal melt.

In Antarctica, calving includes grounded ice that leaves the ice sheet directly into the ocean (not an input to an ice shelf; citet:rignot_2019) and ice shelf calving from citet:greene_2022. We assume that the Antarctic frontal melt component is zero.

Both Antarctic calving and Greenlandic calving and frontal melt assume steady state. That is, in Greenland calving and frontal melt balances grounded ice discharge and does not include frontal advance and retreat. In Antarctica, non-shelf calving balances non-shelf discharge, and ice shelf calving is based on a fixed calving front. See frontal advance and frontal retreat for the non steady state component.

Ice shelf basal melt in Greenland comes from citet:wang_2024, and in Antarctica comes from citet:paolo_2023. 

*** Frontal retreat

The frontal retreat products for Greenland citep:kochtitzky_2023 and Antarctica citep:greene_2022 are one part of the non steady state component of calving and frontal melt processes (the other part being frontal advance). Here we report the product (frontal retreat) not the processes (calving, frontal melt). Frontal retreat is presumably split between frontal melt and calving processes ~50/50 in Greenland citep:rignot_2010 with high uncertainty, and is likely to be primarily calving in Antarctica. Frontal advance is discussed in the Inputs section.

*** Grounding line retreat

Grounding line retreat by definition here only occurs under ice shelves. If there is no ice shelf, it is frontal retreat.

Numerous papers have documented grounding line migration around both Greenland and Antarctica at different spatial and temporal scales (e.g., citet:rignot_2014,konrad_2018,millan_2022_petermann,milillo_2022,picton_2023,li_2023,gadi_2023). However, only one study citep:davison_2023 provides estimates of grounding line migration in the dimensions needed here, mass or length\textsuperscript{3} and time (e.g., (Gt or km^{3}) yr^{-1}) -- they are typically reported in dimensions of length and time (e.g., m yr^{-1}).

We estimate grounding line migration in Greenland for Petermann glacier using  published values of grounding line retreat (units m) from citet:millan_2022, ice thickness from citet:ciraci_2023, and ice density of 917 kg m^{3} to calculate grounding line retreat in units of Gt yr^{-1}. We estimate ~1.5 Gt yr^{-1}. Given the order of magnitude of this result relative to the magnitude of other processes, we round this up to 5 (see Methods > Other > Rounding) to include other remaining Greenlandic ice shelves.

In Antarctica, the fastest rates of ice shelf grounding line retreat are in Amundsen Sea Embayment, contributing 45 Gt yr^{-1} citep:davison_2023. Although grounding line retreat occurs elsewhere in West Antarctica (e.g., at Ferrigno and Venable ice shelves), we ignore these unquantified contributions. They are likely small relative to other terms, but any missing flow directly impacts the residual term calculated via the IO method. citet:konrad_2018 showed that 85 % of all Antarctic ice sheet grounding line retreat (in terms of area change per year, from 2010 to 2016) occurs in West Antarctica. We therefore use 45 Gt yr^{-1} for Antarctica and West Antarctica, and a low estimate of 1 Gt yr^{-1} for East Antarctica and the Peninsula. This value is likely an underestimate, but with no additional information we use it as a placeholder until such time as there is a better estimate of this value.

*** Grounded ice basal melt

Grounded ice basal melt citep:karlsson_2021,van-liefferinge_2013 comes from geothermal heat flux, frictional heat from sliding, and in Greenland but not Antarctica, viscous heat dissipation from surface runoff routed to the bed citep:mankoff_2017_VHD. Ice-sheet wide, the term is split approximately evenly among the two (Antarctica) or three (Greenland) terms. The geothermal flux term is steady state but poorly observed under the ice sheets - only a few ground-truth measurements exist (c.f. citet:colgan_2022), and models of the spatial distribution of geothermal flow show substantial disagreement citep:zhang_2024.

** Inputs

*** Frontal advance

Frontal advance is provided with the frontal retreat from citet:greene_2022 in Antarctica. There is no frontal advance in Greenland provided by the decadal estimates from citet:kochtitzky_2023. Advance (plus retreat) provides the non steady state component of calving in Antarctica, and calving plus frontal melt in Greenland.

Frontal advance is not technically a mass input, but a lack of mass output via reduced calving, which is why it is shown as a truncated input, similar to the mass loss input. The products that provide frontal advance do take into account thinning, so it is mass gain (via reduced mass loss), not just a re-arrangement of the existing mass through expansion where the frontal advance is directly balanced by a reduction in thickness elsewhere.

*** Rainfall, condensation, deposition, and snowfall

These SMB inputs come from the MAR model. In reality, some rainfall leaves directly as runoff or evaporation, as not all precipitation freezes to ice. We neglect this level of detail here for simplicity.

*** Ice shelf basal freeze-on

Ice shelf basal freeze-on from citet:wang_2024 in Greenland and citet:paolo_2023 in Antarctica is provided with the ice shelf basal melt product and is a similar but opposite process. 

** Freshwater mass flow rate

We calculate net freshwater mass flow not simply as the sum of all outputs, but using net, not gross, for some terms due to the physical processes involved. For example, in Antarctica gross ice shelf basal melt is 1375 Gt yr^{-1}, but ice shelf basal freeze-on of 366 Gt yr^{-1} should be subtracted from this value (Table \ref{tab:aq}). Freshwater for freeze-on must be supplied from either grounded ice basal melt (meaning that freshwater mass does not reach the open ocean) or extracted from ocean water that flows under the shelf, temporarily increasing the salinity of sub-shelf water.

This treatment of freshwater mass flow rate is because we are focusing on salinity, and a salt as a tracer is assumed to be rejected during freezing of ocean water. Similarly, if fresh grounded basal meltwater is frozen, then that water does not leave the system. In these cases, a unit freeze-then-melt has no impact on the net tracer value. The process is assumed to be conservative (i.e., no external change).

Similarly, when considering total freshwater export, or salinity, gross frontal retreat and gross frontal advance should be combined to net frontal change.

We warn that other use cases should carefully consider assumptions of tracer treatment, for example, if a tracer is not conserved during a freeze-then-melt cycle, then gross terms should be used.

** Mass loss and gain

We calculate mass loss and gain from the sum of all outputs minus inputs.

** Uncertainty

#+begin_src jupyter-python :var tbl=README.org:gl_baseline :colnames no :exports none
import numpy as np
import pandas as pd

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.drop(columns=['Period','Source','IO'])

df = df.set_index('Term')
df = df[df['Value'] != '0']
df['Unc.'] = df['Unc.'].replace({'?':'100'})

for i,v in zip(df.index,df['Value']):
    df.loc[i,'Value'] = eval(v)
df['Value'] = df['Value'].astype(int)
df['Unc.'] = df['Unc.'].astype(int)

weight = (df['Value'] * df['Unc.']).sum() / df['Value'].sum()
print('GL:', weight)
#+END_SRC

#+RESULTS:
: GL: 17.1875

#+begin_src jupyter-python :var tbl=README.org:aq :colnames no :exports none
import numpy as np
import pandas as pd

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.drop(columns=['Period','Source','IO'])
df = df.set_index('Term')
df['Unc.'] = df['Unc.'].replace({'?':'100','5 -- 50':'100', '':'0'})

cols = ['East_g','West_g','Peninsula_g','East_s','West_s','Peninsula_s','Unc.']
for c in cols:
    df[c] = df[c].astype(int)

df['E'] = df['East_g'] + df['East_s']; df = df.drop(columns=['East_g', 'East_s'])
df['W'] = df['West_g'] + df['West_s']; df = df.drop(columns=['West_g', 'West_s'])
df['P'] = df['Peninsula_g'] + df['Peninsula_s']; df = df.drop(columns=['Peninsula_g', 'Peninsula_s'])
df['A'] = df['E'] + df['W'] + df['P']

cols = ['E','W','P','A']
for c in cols:
    weight = (df[c] * df['Unc.']).sum() / df[c].sum()
    print('AQ:', c, weight)
#+end_src

#+RESULTS:
: AQ: E 58.9046365661065
: AQ: W 71.11833010782416
: AQ: P 51.60362490149724
: AQ: A 62.458015267175576

Uncertainty on most individual terms is provided by the upstream data products and presented in the uncertainty ("Unc." column) in Tables \ref{tab:gl} and \ref{tab:aq}. The exceptions are calving and frontal melt in Greenland, net freshwater mass flow rate, and the derived mass loss and gain terms.

Calving and frontal melt uncertainty is 30 % between those two, but combined is 10 % constrained by the upstream discharge term (see Discussion > Uncertainty).

For net freshwater mass flow rate we use gross values for ice shelf basal melt and frontal retreat, treat each term as independent, and report the square root of the sum of the squared uncertainties.

For derived mass loss, mass gain, and uncertainty, traditional uncertainty propagation leads to unreasonably large numbers, because the values are large and the residual is small. We therefore estimate the residual uncertainty using the weighted uncertainty for each term in Tables \ref{tab:gl} and \ref{tab:aq}. Using this method, Greenland uncertainty is 15 %, and Antarctic uncertainty is 60 % in the East, 70 % in the west, 50 % in the Peninsula, and 60 % overall.

A comparison of our mass change and uncertainty results with mass change and uncertainty from the independent GMB method citep:groh_2019 shows an agreement between the two. Our uncertainty is consistently larger for the same domain, and our estimates well are within the GMB uncertainty (Table \ref{tab:results_mc}).

** Other

*** Separation of Antarctic regions

In Antarctica, we use the MEaSUREs Antarctic Boundaries for IPY 2007-2009 from Satellite Radar, Version 2 (NSIDC product 0709; citet:mouginot_2017,rignot_2013) to separate Antarctica into East, West, and Peninsula. Discharge from Antarctic islands is reported once for all islands by citet:rignot_2019. In order to separate island discharge by region, we find the area of all islands per region, and divide the discharge proportional to area. This implicitly assumes that discharge from each island scales linearly with the area of each island.

*** Peripheral glaciers

In Antarctica it is not easy to define or remove peripheral glaciers. We are also including floating ice, which is moves the focus away from the traditional assessments of `grounded ice sheet' to a more holistic view of `regional ice sheet health'. It naturally followed to include peripheral glaciers in Greenland too.

*** Temporal alignment

Most values come from time series that we limit to 2010 through 2019, or are provided for that time span. Some values cover different periods, and in these cases we use the closest available time span to 2010 through 2019 (Tables \ref{tab:gl} and \ref{tab:aq}.). The impact of non-overlap is a function of the scale and variability of the term.

The largest shift in Greenland is 2013 -- 2022 vs the baseline 2010 -- 2019, or approximately a 30 % non-overlap. The term is the ice shelf melt and freeze product which is small, and we estimate the variability as medium due to the oceanic forcing. It is less variable than atmospherically controlled SMB terms (which also happen to be large) and more variable than terms controlled by glacier large-scale dynamics.

The largest shift in Antarctica is 1997 - 2021 vs the baseline 2010 -- 2019. As discussed this term is not defined outside of the Amundsen sea sector, and remains an important area for future studies to help reduced uncertainties and close the budget of the ice sheet mass balance work presented here.

*** Rounding

In Table \ref{tab:aq} we round to the nearest whole number, except values between 0 and 0.5 which are rounded up to 1. Everywhere else values are rounded to the nearest 5, except values between 0 and 2.5 which are rounded up to 5. We choose to round because because sub-decimal precision of terms presented here seems unlikely to be correct, even if it is correct it is not relevant to results, and for aesthetic reasons.

* Results

All mass flow terms and values for each term are shown in Tables \ref{tab:gl} and \ref{tab:aq} and the Sankey diagrams. In addition, the tables contain the time span of each value and reference publication. Net freshwater mass flow rates are shown in Table \ref{tab:results_fw} and net mass loss by region and grounded vs floating ice are shown in Table \ref{tab:results_mc}.

** Sankey diagrams                                        :ignore:

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{gl_baseline.pdf}}
\caption{Sankey mass flow diagram for Greenland. Numbers are mass flow rate [Gt yr\textsuperscript{-1}]. All widths are proportional within and between images. Gray is solid phase, blue is liquid phase, and yellow is gas phase. Inputs (left, arrow tail) are balanced by outputs (right, arrow head) and come from IO column of Table \ref{tab:gl}. Because Sankey diagrams balance all inputs and outputs, mass losses require an input to balance the larger outputs.}
\label{fig:gl}
\end{figure*}

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{aq_All.pdf}}
\caption{Sankey mass flow diagrams for Antarctica. See Fig. \ref{fig:gl} for legend and details.}
\label{fig:aq}
\end{figure*}

** Freshwater mass flow rate

Net freshwater export to the ocean (mass loss terms excluding sublimation and evaporation) is 1065 \pm120 Gt yr^{-1} for Greenland and 3110 \pm1515 Gt yr^{-1} for Antarctica. Antarctic sub-region values are also provided in Table \ref{tab:results_fw}, along with values in Sverdrup or 10^6 m^3 s^{-1}.

# Greenland table net freshwater flow
#+begin_src jupyter-python :var tbl=README.org:gl_baseline :colnames no :exports none
import numpy as np
import pandas as pd

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.drop(columns=['Period','Source'])

df = df.set_index('Term')
df = df[df['IO'] != 'I_g']
df = df[df['IO'] != '']
df = df[df['Value'] != '0']
df['Unc.'] = df['Unc.'].replace({'?':'100'})

for i,v in zip(df.index,df['Value']):
    df.loc[i,'Value'] = eval(v)
    df['Value'] = df['Value'].astype(int)
    df['Unc.'] = df['Unc.'].astype(int)
    df.loc['Ice shelf basal freeze-on', ['Value','Unc.']] = -1* df.loc['Ice shelf basal freeze-on', ['Value','Unc.']]

df['Err'] = df['Value'] * (df['Unc.']/100)
r = np.sum(unumpy.uarray(df['Value'].values, np.abs(df['Err'].values)))
print(r.n, r.s)
#+end_src

#+RESULTS:
: 1065.0 120.11921161912444

#+NAME:tab:results_fw
#+begin_src jupyter-python :var tbl=README.org:aq :colnames no :exports results
import numpy as np
import pandas as pd

tblout = pd.DataFrame(index=['Greenland','Antarctica','Antarctica East',
                            'Antarctica West','Antarctic Peninsula'],
                      columns=['FW','Err'])

tblout.loc['Greenland'] = [1065,120]

tbl = np.array(tbl)
df = pd.DataFrame(tbl[1:,1:], index=tbl[1:,0], columns=tbl[0,1:])

df = df.drop(columns=['Period','Source'])
df = df.set_index('Term')
df = df[df['IO'] != '']
df = df.drop(['Frontal melt','Sublimation','Evaporation'])
df['Unc.'] = df['Unc.'].replace({'?':'100'})

cols = ['East_g','West_g','Peninsula_g','East_s','West_s','Peninsula_s','Unc.']
for c in cols:
    df[c] = df[c].astype(int)

# frontal advance  and ice shelf basal freeze-on should be treated as negative outputs
cols = ['East_g','West_g','Peninsula_g','East_s','West_s','Peninsula_s']
df.loc['Frontal advance',cols] = -1*df.loc['Frontal advance',cols]
df.loc['Frontal advance','IO'] = 'O'
df.loc['Ice shelf basal freeze-on',cols] = -1*df.loc['Ice shelf basal freeze-on',cols]
df.loc['Ice shelf basal freeze-on','IO'] = 'O'

df.loc['Front adv and ret'] = df.loc['Frontal retreat'] + df.loc['Frontal advance']
df.loc['Front adv and ret','Unc.'] = df.loc['Frontal retreat','Unc.']
df.loc['Ice shelf melt and freeze'] = df.loc['Ice shelf basal melt'] + df.loc['Ice shelf basal freeze-on']
df.loc['Ice shelf melt and freeze','Unc.'] = df.loc['Ice shelf basal melt','Unc.']
df = df.drop(['Frontal advance','Frontal retreat','Ice shelf basal freeze-on','Ice shelf basal melt'])


df = df[df['IO'] != 'I']
df = df.drop(columns='IO')

for c in df.columns:
     df[c] = df[c].astype(int)
df['E'] = df['East_g'] + df['East_s']; df = df.drop(columns=['East_g', 'East_s'])
df['W'] = df['West_g'] + df['West_s']; df = df.drop(columns=['West_g', 'West_s'])
df['P'] = df['Peninsula_g'] + df['Peninsula_s']; df = df.drop(columns=['Peninsula_g', 'Peninsula_s'])
df['A'] = df['E'] + df['W'] + df['P']

r = np.sum(unumpy.uarray(df['E'].values, np.abs(df['E'].values * (df['Unc.']/100))))
tblout.loc['Antarctica East','FW'] = r.n
tblout.loc['Antarctica East','Err'] = r.s

r = np.sum(unumpy.uarray(df['W'].values, np.abs(df['W'].values * (df['Unc.']/100))))
tblout.loc['Antarctica West','FW'] = r.n
tblout.loc['Antarctica West','Err'] = r.s

r = np.sum(unumpy.uarray(df['P'].values, np.abs(df['P'].values * (df['Unc.']/100))))
tblout.loc['Antarctic Peninsula','FW'] = r.n
tblout.loc['Antarctic Peninsula','Err'] = r.s

r = np.sum(unumpy.uarray(df['A'].values, np.abs(df['A'].values * (df['Unc.']/100))))
tblout.loc['Antarctica','FW'] = r.n
tblout.loc['Antarctica','Err'] = r.s

tblout['Sv'] = tblout['FW'] * 0.0000316887
tblout['Sv Err'] = tblout['Err'] * 0.0000316887

tblout['FW'] = (tblout['FW']/5).round().astype(int)*5
tblout['Err'] = (tblout['Err']/5).round().astype(int)*5
tblout['Sv'] = tblout['Sv'].astype(float).round(3)
tblout['Sv Err'] = tblout['Sv Err'].astype(float).round(3)

tblout['FW'] = tblout['FW'].astype(str) + ' \pm' + tblout['Err'].astype(str)
tblout['Sv'] = tblout['Sv'].astype(str) + ' \pm' + tblout['Sv Err'].astype(str)
tblout = tblout.drop(columns=['Err','Sv Err'])

tblout = tblout.rename(columns={'FW':'Gt yr^{-1}'})
# df
tblout
#+end_src

#+ATTR_LATEX: :column{1}={gray9}
#+CAPTION: Net freshwater export mass flow rate for Greenland, Antarctica, and Antarctic regions in Gt yr^{-1} and Sverdrup (10^6 m^3 s^{-1}).\label{tab:results_fw}
#+RESULTS: tab:results_fw
|                         | Gt yr^{-1}   | Sv             |
|-------------------------+--------------+----------------|
| Greenland               | 1065 \pm120  | 0.034 \pm0.004 |
| Antarctica              | 3110 \pm1515 | 0.099 \pm0.048 |
| \phantom{Ant} East      | 1160 \pm480  | 0.037 \pm0.015 |
| \phantom{Ant} West      | 1420 \pm805  | 0.045 \pm0.026 |
| \phantom{Ant} Peninsula | 530 \pm225   | 0.017 \pm0.007 |

** Mass change

Mass change for the 2010 through 2019 period is net mass loss for Greenland, West Antarctica, the Antarctic Peninsula, and Antarctica as a whole, but net mass gain in East Antarctica (Table \ref{tab:results_mc}).

Greenland lost 255 \pm40 Gt yr^{-1} from grounded ice and an additional 75 \pm10 Gt yr^{-1} (30 %) from floating ice.

Antarctica lost 190 \pm115 Gt yr^{-1} from grounded ice and an additional 260 \pm155 Gt yr^{-1} (~140 %) from floating ice. The grounded ice mass loss is partitioned with 250 \pm190 Gt yr^{-1} lost from West Antarctica and 20 \pm10 Gt yr^{-1} lost from the Peninsula offset by 80 \pm50 Gt yr^{-1} gained in East Antarctica. Floating ice mass losses are partitioned with 275 \pm190 Gt yr^{-1} lost from West Antarctica and 175 \pm85 Gt yr^{-1} lost from the Peninsula offset by 190 \pm115 Gt yr^{-1} gained in East Antarctica.

In comparison, estimated net grounded ice mass loss by the GMB method is 226 \pm15 Gt yr^{-1} (we round this up to ~10 %) in Greenland citep:dohne_2023 and 151 \pm44 Gt yr^{-1} (~30 %) in Antarctica citep:groh_2021. The Antarctic regions have uncertainty of 115 %, 10 %, and 35 % for the East, West, and Peninsula respectively.

# GL net: 330
# GL ground (subtract marine loss, add marine gain): 330-50-5-25+5 = 255
# GL marine: 330 - 255 = 75

#+NAME:tab:results_mc
#+CAPTION: Net mass change flow rate and uncertainty. Grounded, floating, and total columns are estimates from this paper. Uncertainty estimates come from a GMB uncertainty assessment described by citet:groh_2019. \label{tab:results_mc}
| Region     |            Grounded |              Floating |                 Total | Unc |          GMB | Unc. |
|            |        [Gt yr^{-1}] |          [Gt yr^{-1}] |          [Gt yr^{-1}] | [%] | [Gt yr^{-1}] |  [%] |
|------------+---------------------+-----------------------+-----------------------+-----+--------------+------|
| /          |                 <r> |                   <r> |                   <r> | <r> |          <r> |      |
| /          |                     |                       |                       |     |            < |      |
| Greenland  |          -255 \pm25 |  -75 \pm10\phantom{0} | -330 \pm35\phantom{0} |  15 |   -226 \pm15 |   10 |
| Antarctica |          -190 \pm60 | -260 \pm80\phantom{0} |           -450 \pm140 |  60 |   -151 \pm45 |   30 |
| East       |            80 \pm90 |           190  \pm220 |            270 \pm310 |  60 |     35 \pm40 |  115 |
| West       |          -250 \pm25 | -275 \pm30\phantom{0} | -525 \pm55\phantom{0} |  70 |   -165 \pm15 |   10 |
| Peninsula  | -20 \pm5\phantom{0} | -175 \pm60\phantom{0} | -15  \pm65\phantom{0} |  50 |    -21 \pm10 |   35 |

* Discussion

** Constituent terms and net versus gross

We recommend to the community to report all the constituent terms of mass change as well as the gross values, and not only the net values. If needed, it is relatively straightforward to include a net combined term. There are numerous advantages to this approach. More information is better. Constituent term level details are needed to properly quantify and attribute differences in SMB model inter-comparison studies (e.g., citet:mottram_2021).
The potential benefits for future researchers to address currently-unknown research questions or undefined needs is likely to outweigh the costs of increased complexity, time, storage, and access.

Sea level rise research often focuses on how and why, not only how much. Process level detail is needed to provide model inputs or validation for the how and why. However even the IO method that provides process level detail is usually estimated with a single SMB value rather than  constituent terms as shown here, and may miss important information. For example, if net SMB remains constant over time, but snowfall and runoff both increase, this indicates a different ice sheet state, and this information should not be removed through reporting of net values.

The largest input, by far, is snowfall in Antarctica. Unfortunately, this process involves integrating small values over a large area, which introduces high uncertainty. The second largest term in Antarctica is calving, but unlike snowfall this occurs in large quantities from just a few ice shelves. Continued production, maintenance, and improvement of these datasets to generate robust time series is essential for monitoring ice sheet health and improving our understanding of processes contributing to sea level rise.

Finally, although we argue for gross, not net, and inclusion of constituent terms in general when sharing outputs, we caution that any users should consider if this is the correct treatment for their application. As discussed in the Methods, use cases should carefully consider assumptions of tracer treatment, for example, if a tracer is not conserved during a freeze-then-melt cycle. By providing constituent and gross terms, we hope this data set is still useful for these scenarios.

# For any given term - basal melt and freeze-on being a likely candidate for freshwater studies - it may be more correct to use net not gross.

** Net mass loss and gain

We have been using the terms `mass loss' vs `mass gain' or `drawdown or retreat' vs `build-up or expansion'. The specific cause of these processes can be thought of as a recursive application of the methods, tables, and graphics here. That is, the imbalance is due to changes from some balanced baseline and the changes are likely all of the terms here - decreases or increases of inputs offset by decreases or increases of outputs.

For example, the `mass loss' input in Fig. \ref{fig:gl} could be an inset Sankey diagram showing changes in all of the terms relative to some steady-state baseline. Similarly, the value in a table for a `mass loss' key could be a single value, or a nested table showing all the terms that contribute to that value. 

** Freshwater export, mass loss, and anomalies

Oceanographic models often use ice sheet freshwater export as a forcing, but it can be challenging for those model developers to find appropriate inputs in part because some models are coupled to ice sheet models, or global climate models with ice sheets, that contain some but not all processes. Ocean models and modelers then need to understand what processes are and are not included in the ice sheet outputs, and for the processes that are included, they may need to determine the anomalies and then add that to the ocean model \citep[c.f.,][]{schmidt_2023}.

# Freshwater export and mass loss (not mass flow) are, occasionally, treated as a similar process. That is not the case. Sectors of ice sheets can gain mass and yet still have large freshwater export, as long as the winter snowfall (or other mass inputs) offsets the mass loss terms. When working in anomaly space, the difference between mass anomaly (mass change) and freshwater anomaly can be more complicated. An ice sheet or sector can gain mass over time, while increasing freshwater discharge over time too. There is a correlation between the two processes, but they are not necessarily tightly coupled.

The smaller terms shown here are commonly excluded because they are small, but ocean modelers who work with anomalies should be careful of excluding these small terms. These smaller terms are also often less likely to be included in the ice component driving or coupled to the ocean model. Their inclusion should be considered, if appropriate, in the ocean model because these small processes can match the magnitude of the anomaly, especially if several of the smaller terms are combined.

** Uncertainty

# Sankey diagrams do not typically include a display of uncertainty, although it is possible to add a visual indicator to the graphic citep:vosough_2019. We do not include a display of uncertainty in the graphics, but do in the tabular display (Tables \ref{tab:gl} and \ref{tab:aq}). Uncertainty values come from the upstream published products that are inputs to this work.

Uncertainty on the derived mass loss and mass gain terms is difficult to quantify because these terms are residuals - the small difference of several large numbers, some with large uncertainty. This is one of the major weaknesses of the IO method which is primarily used here. A basic uncertainty propagation could assume each term is independent (they are not) and report the residual values of mass loss and gain as the square root of the sum of the square of the individual uncertainty estimates. This calculation is trivial and this method produces a number, but it is unreasonably large.

# As seen in Table \ref{tab:results_fw} uncertainty calculated using this method is ~50 % of the net freshwater exported from Antarctica. Net freshwater export excludes inputs that do not impact freshwater export (e.g., it includes ice shelf freeze-on, but excludes snowfall) so the uncertainty would be considerably larger if adding 15 % uncertainty from the ~2800 Gt yr^{-1} snowfall inputs.

A comparison of the estimated net grounded ice mass loss with results of the independent GMB method (Table \ref{tab:results_mc}) indicates a much better agreement between the two methods than suggested by a basic uncertainty propagation of all IO terms. The independently assessed uncertainty for the GMB method better fits to the differences in estimates for all regions under investigation (e.g., for Antarctica the difference between the two methods is 39 Gt yr^{-1} and the uncertainty of the GMB estimate is 45 Gt yr^{-1}). Using the GMB uncertainty as our derived residual uncertainty may be appropriate, and would provide a much smaller uncertainty than the values we report here. However, we only use the GMB uncertainty to provide context because there is no physical basis and mathematical connection between the mass change estimates (residual from the IO method) and the mass change uncertainty (from the GMB method).

# . These percentages, and the decision to apply them to floating ice, are derived using the judgment of the authorship team and knowledge of other independent products that directly measure mass change and can therefore better constrain uncertainty than the IO method used here.

# We therefore use the uncertainties of the GMB method as a rough approximation of the derived mass loss and mass gain uncertainty. We calculate the uncertainty as a percentage of the GMB estimate and apply that uncertainty to both, our grounded and floating mass change.


# *** SMB Uncertainty

# The most common uncertainty value of 15 % comes from the MAR RCM, but the RCM uncertainty is derived from net SMB, not the individual constituent terms \cite[c.f.,][]{colgan_2015}. If the 15 % SMB uncertainty is applied to each term as done here and then summed to SMB using traditional mathematical uncertainty propagation of independent variables (a physically incorrect assumption), SMB is 235 Gt yr^{-1} and uncertainty is 122 Gt yr^{-1} or ~50 %. This is due to the large snowfall and runoff relative to other terms.

# The sum of seven equal terms with 15 % uncertainty treated independently, is 5.6 %.

*** Greenlandic discharge, calving, and frontal melt uncertainty

Discharge uncertainty in Greenland is reasonably well constrained at ~10 % by citet:mankoff_2020_solid and other similar products.

The division of discharge when it is divided into submarine melt and calving is highly uncertain. citet:rignot_2010 reports "We conclude from this comparison that 20--80% of the summer ice-front fluxes are directly melted by the ocean" with the remainder coming from calving. But that study only examined a few glaciers for a relatively short period of time. From this, we split discharge 50/50 between frontal melt and calving (see Methods), and assign an uncertainty of 30 %. However, in this case, the two terms are not independent. They are highly dependent, constrained by the upstream discharge with 10 % uncertainty. It is only the separation and form or phase (solid or liquid) that is highly uncertain.

*** Antarctic Discharge

Discharge and discharge uncertainty in Antarctica is challenging to quantify. At the low end, citet:rignot_2019 reports uncertainty of ~5 % on the discharge term. This seems unlikely for several reasons, including that discharge uncertainty in Greenland is more than 5 % and bed topography -- the main source of discharge uncertainty -- is better constrained there, or that citet:rignot_2019 calculates discharge using a corrective scaling factor ranging from 0.62 to 4.57 and relies on 5 separate methods (that are applied in isolation, not constraining each other).

# 429/1839 % = 23.3278955954

At the high end, citet:davison_2023 report a cumulative discharge (from grounded ice to ice shelves) change of 1770 \pm 870 Gt which is ~50 %, but Antarctic-summed steady state discharge for ~1840 \pm ~125 Gt yr^{-1} which is ~5 %.


** Missing terms, limitations, and simplifications
\label{sec:limits}

These figures and tables neglect some mass flow processes (some of which are included in \citet[][Figure 2]{cogley_2011}, and simplify others.

Neglected processes include grounded ice basal freeze-on (c.f., citet:bell_2014). Grounded ice basal melt estimates currently assume all melt leaves the ice sheet and is therefore mass loss. That seems unlikely, given both observations of freeze-on citep:bell_2014 and that some melt, especially from the geothermal term (c.f., citet:karlsson_2021) occurs under thick ice far inland and far from active subglacial conduits. That is, there should be a separate term and second `refreezing' loop at the bottom of the Sankey diagrams to represent basal refreezing.

Sub-aqueous frontal melt is excluded in Antarctica, because it is usually excluded in the literature that focuses on ice shelf basal melt or calving. This term is implicitly included in the calving estimates. This process remains unquantified on ice-sheet wide scales.

Subaerial frontal melt and sublimation of the vertical face above the water line \cite[][Figure 2]{cogley_2011} is not explicitly treated but is included in other terms.

Grounding line retreat in both Greenland and Antarctica is largely unquantified in the units needed to include it here, as discussed in the methods.

We neglect avalanche on and off ice sheets - these likely matter more for mountain glaciers.

Snow drift on and off is also excluded. There is likely little snow drift onto either ice sheet, but drifting off may be of similar magnitude to some of the other smaller terms shown here.

# + There may be other as-yet unidentified missing terms. For example, the earlier version of this graphic by \citet[Fig. 2]{cogley_2011} did not contain frontal nor grounding line retreat. These are two distinct processes when ice shelves exist, but can be treated as synonyms for one process at tidewater glacier margins. These terms were not only not included in citet:cogley_2011, but their respective values were highly uncertain, and still are, although recent work by citet:kochtitzky_2023,greene_2024 have constrained these values in Greenland. 

This work focuses on Greenlandic and Antarctic ice masses as a freshwater source. There are other sources and sinks of freshwater into the oceans around Greenland and Antarctica not covered here, including but not limited to: rain and snow melt from non-ice covered ground in Greenland citep:mankoff_2020_liquid, rain and snow directly onto the fjord or ocean surface, evaporation over the surrounding oceans, and sea ice growth, movement, and melt.

There are a variety of simplifications. For example, not all rainfall input turns to ice as depicted by the arrows in these diagrams. Some enters as part of the refreezing loop, and some remains liquid and leaves as runoff or evaporation. Similarly, the evaporation output could pull from the refreezing loop (in the liquid phase, depicted by the blue color) and also directly from rainfall as stated above. Although some path details are simplified, the magnitudes are still as reported in the input products. Furthermore, the simplifications we are aware of are all a very small component relative to the total freshwater or mass flow or even the mass imbalance.

*** Temporal resolution of input observations

The value of some terms presented here are biased by the temporal resolution of the upstream product that is an input to this work. This is the case for all terms until the observations are instantaneous, but impacts bi-directional processes like advance and retreat or step change processes like calving more than slowly varying processes like discharge. For example, in Greenland we report 50 Gt yr^{-1} frontal retreat and 0 Gt yr^{-1} frontal advance using decade-scale reporting from citet:kochtitzky_2023. However, that is a decadal net term despite the majority of this work reporting gross terms, and sub-decadal advances are not captured there.

Given a theoretical reference front location for calving and frontal melt, \(X\) Gt of frontal retreat may actually be \(X + Y\) Gt frontal retreat offset by \(Y\) Gt frontal advance that occurred at a temporal resolution below the observations. This does not matter for total freshwater mass which should be calculated using net frontal change, not gross frontal retreat. Ice shelf basal freeze-on and melt share some similar temporal resolution dependent issues, and a decision to use net or gross is dependent on the use case.

* Summary

Previous estimates of mass loss for Greenland and Antarctica show a range of values citep:otosaka_2023, highlighting the need for improved estimates and a common framework for accounting of ice sheet mass balance. The work presented here offers one such framework that could be adopted by the community for future balance estimates.

In this work we report total ice sheet and peripheral glacier mass change for both Greenland and Antarctica for the 2010 through 2019 period, reporting not just grounded ice mass loss, but also changes in floating ice. We have provided all available constituent terms and gross not net values. This detailed information provides a better picture of ice sheet health than focusing only on mass loss or only on grounded ice.

We have also displayed these constituent terms and net values using Sankey diagrams which provide an information-dense display showing a) the relations between terms and processes, b) quantitative display of the magnitude of each term, and c) visual comparisons between different ice sheets or sub-regions of ice sheets, as the magnitude of the graphic uses the same proportion between all images.

* References                                              :ignore:

\bibliography{library}
\bibliographystyle{igs}

* Author contributions

#+NAME: tab:credit
#+BEGIN_SRC jupyter-python :exports results
import pandas as pd
df = pd.read_csv('credit.csv', skiprows=1)
df['Initials'] = [''.join([c for c in _ if c.isupper()]) for _ in df['First']]
df['Initials'] += [_[0] if _ != 'foo' else '' for _ in df['Middle'].fillna('foo')]
df['Initials'] += [_[0] for _ in df['Last']]
df = df.drop(columns=['First','Middle','Last','Affiliation1','Affiliation2','Affiliation3','ORCID'])
df = df.set_index('Initials').T

s = df.sum()
df = df[s.sort_values(ascending=False).index]
df = df.replace(np.nan, '')
df = df.replace(1, '\\checkmark')

df.T
#+END_SRC

#+CAPTION: Author contributions following the CRediT system citep:allen_2019,brand_2015,allen_2014
#+RESULTS: tab:credit
| Initials   | Data       | Graphic    | Write      | Edit       | Discuss    |
|------------+------------+------------+------------+------------+------------|
| KDM        | \checkmark | \checkmark | \checkmark | \checkmark | \checkmark |
| CAG        | \checkmark |            |            | \checkmark | \checkmark |
| BD         | \checkmark |            |            | \checkmark | \checkmark |
| TD         | \checkmark |            |            | \checkmark | \checkmark |
| DT         |            |            |            | \checkmark | \checkmark |
| WK         |            |            |            | \checkmark | \checkmark |
| XF         | \checkmark |            |            |            | \checkmark |
| DR         |            | \checkmark |            |            | \checkmark |
| ASG        |            |            |            | \checkmark | \checkmark |
| CQK        | \checkmark |            |            |            |            |
| GW         | \checkmark |            |            |            |            |
| BVL        | \checkmark |            |            |            |            |
| RF         |            |            |            |            | \checkmark |

* Conflict of Interest

No authors have any conflict of interest with the work presented here.

* Acknowledgments

Funding: KDM was supported by the NASA Modeling, Analysis and Prediction program. ASG and CAG contributions were carried out at the Jet Propulsion Laboratory, California Institute of Technology, under a contract with the National Aeronautics and Space Administration (80NM0018D0004).

People: We thank Andreas Ahlstrøm and Nanna Karlsson for additional comments on this paper, and Kristin Poinar for suggesting improvements to the Sankey figure. We thank Aman KC and two additional reviewers for their comments that helped improved the manuscript.

Software: We thank citep:sankey for the \LaTeX\enspace TikZ Sankey package, and citet:cogley_2011 for a reference graphic. Analysis was aided by the software packages Pandas citep:pandas_team, GeoPandas citep:geopandas, Xarray citep:xarray, and GRASS GIS citep:GRASS, among other tools.

* Appendix                                                :ignore:
\appendix
* Appendix A: Sankey diagram tools
\label{appendix:sankey}

There are several software packages that support creating Sankey diagrams with various levels of complexity and control. The four applications we found, in order from easiest and most limited to most complex and feature-full are the Mermaid diagram tool, Plotly (which can be used from Python, R, or other popular languages), Matplotlib, and finally \LaTeX.

The simplest Mermaid option is produced with only a CSV file of the format 'in,out,value'. Neither order nor closure (balance) is important, and a user has limited control over layout and color, although a user can edit things later manually if generating SVG format. We used Mermaid to generate the Sankey diagram in Appendix C, and the source for this diagram can be found in the supplemental source at https://doi.org/10.5281/zenodo.15819650 file =mermaid.org=. Mermaid diagrams in Markdown files on GitHub render directly in the browser from the data (no saved image file).

The main Sankey diagrams shown here are generated using a \LaTeX\enspace template that uses the TikZ Sankey package citep:sankey. We use a script that inserts CSV tables into the template. This architecture makes it trivial to generate similar diagrams for other time periods (e.g., a Sankey diagram per year), differences between time periods, other regions (for example, on diagram per glacier basin), etc.

* Appendix B: Antarctic mass flow by region

\label{appendix:aq_regions}

Figure \ref{fig:aq_regions} shows Antarctica (Fig. \ref{fig:aq}) split by East, West, and Peninsula regions

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{aq_E.pdf}}
\centering{\includegraphics[width=0.85\textwidth]{aq_W.pdf}}
\centering{\includegraphics[width=0.85\textwidth]{aq_P.pdf}}
\caption{Sankey mass flow diagrams for three Antarctica regions: East (top), West (middle), and Peninsula (bottom). Numbers are mass flow rate [Gt yr\textsuperscript{-1}]. All widths are proportional within and between images. In East Antarctica mass gain is an output at the bottom that balances the diagram, because without it, there are more flows into the system than out of it.\label{fig:aq_regions}}
\end{figure*}

* Appendix C: Alternative display of Antarctic mass flow: grounded vs shelf
\label{appendix:sankey_alternate}

The main Sankey diagrams shown here (Figs. \ref{fig:gl} and \ref{fig:aq}) are simplistic representations of mass flow across the three ice sheet boundaries (atmospheric, subglacial, and oceanic). We combine all inputs and outputs, not distinguishing between inputs over grounded ice vs. inputs over ice shelves, or other display options. However, alternate displays are possible. Fig. \ref{fig:aq_complex} is an example of a more complex display, and separates inputs and outputs by region (grounded, floating) in Antarctica.

This display choice clearly separates grounded and floating ice, but makes it challenging to see, for example, net SMB terms which are readily available in Figs. \ref{fig:gl}, \ref{fig:aq}, and \ref{fig:aq_regions}. Even more involved displays with more branches (and possibly crossed paths) could show all relevant terms both in isolation (e.g., by region and process) and in combination.

\begin{figure*}
\centering{\includegraphics[width=0.95\textwidth]{mermaid_AQ_gray.png}}
\caption{Sankey mass flow diagrams for Antarctica split by grounded (top) vs. floating ice (bottom). Upper and lower figure should be merged at black line, where mass flow output from grounded ice is mass flow input to ice shelves. Numbers are mass flow rate [Gt yr\textsuperscript{-1}].\label{fig:aq_complex}}
\end{figure*}


* LaTeX Setup                                           :noexport:
#+NAME: jog-latex-setup
#+BEGIN_SRC elisp
(add-to-list 'org-latex-classes
               `("igs"
                 "\\documentclass{igs}
               [NO-DEFAULT-PACKAGES]
               [NO-PACKAGES]
               [EXTRA]"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )

(org-add-link-type
 "citet"  (lambda (key) (kdm/org-pdf-open key))
 (lambda (path desc format)
   (cond
    ((eq format 'latex) (format "\\cite{%s}" path))
    ((eq format 'ascii) (format "%s" desc))
    )))
(org-add-link-type
 "citep"  (lambda (key) (kdm/org-pdf-open key))
 (lambda (path desc format)
   (cond
    ((eq format 'latex) (format "\\citep{%s}" path))
    ((eq format 'ascii) (format "%s" desc))
    )))

(setq-local org-latex-title-command "")
#+END_SRC

#+RESULTS: jog-latex-setup

* TODO QC                                               :noexport:

(langtool-check)
(langtool-correct-buffer)
(langtool-check-done)

Export as ASCII, then,

#+BEGIN_SRC elisp :results none :eval no-export
(setq org-ascii-text-width 80)
(org-ascii-export-to-ascii)
#+END_SRC

#+BEGIN_SRC bash :cmdline "-i" :results output :eval no-export :exports none
this='ms.txt'
aspell list < $this | sort | uniq
echo "\n"

declare -a cmds=("style" "diction -s")
for cmd in "${cmds[@]}"; do
    echo "###\n### $cmd\n###"
    #echo $cmd $this
    ${cmd} ${this}
    echo "\n"
done
#+END_SRC

