
:settings_drawer:
#+Latex_Class: igs
#+AUTHOR: 
#+DATE: 
# #+LaTeX_CLASS_OPTIONS: [jog,oneside,review]
#+LaTeX_CLASS_OPTIONS: [jog,oneside]
#+Options: toc:nil ^:t {}:t title:nil

#+EXPORT_FILE_NAME: ms.tex

#+EXCLUDE_TAGS: noexport

#+LATEX_HEADER_EXTRA: \usepackage[utf8]{inputenc}
#+LATEX_HEADER_EXTRA: \usepackage{mathabx}
#+LATEX_HEADER_EXTRA: \usepackage{graphicx}
#+LATEX_HEADER_EXTRA: \usepackage{siunitx}
#+LATEX_HEADER_EXTRA: % \setcounter{secnumdepth}{2}

#+LATEX_HEADER_EXTRA: \jourvolume{V}
#+LATEX_HEADER_EXTRA: \jourissue{N}
#+LATEX_HEADER_EXTRA: \jourpubyear{YYYY}

#+PROPERTY: header-args:jupyter-python+ :dir (file-name-directory buffer-file-name) :session sankey
:end:

#+BEGIN_EXPORT LaTeX
\title[Sankey mass flows]{Ice sheet mass flows}

\author[Mankoff and others]
{Kenneth D. MANKOFF,$^{1,2}$}

\affiliation{%
$^1$NASA Goddard Institute for Space Studies, New York NY USA\\
$^2$Autonomic Integra LLC, New York NY USA\\
Correspondence: Ken Mankoff
\email{ken.mankoff@nasa.gov}}
#+END_EXPORT

#+LATEX: \begin{frontmatter}
#+LATEX: \maketitle

Author list: https://drive.google.com/drive/folders/1g9vXuQofIL5MgtrtQ2zzlLiu69j1kTvJ?usp=sharing

Please add ORCID and Affiliation to CRediT file there.

#+LATEX: \begin{abstract}

Understanding the processes involved in ice sheet mass loss requires knowledge production and sharing, in addition to field observations and computer modeling. Tabular data are optimized for computers and useful for humans, but graphical presentations can provide significantly higher information density. Here we present several Sankey diagrams depicting all mass flow of ice in various phases in Greenland and Antarctica.

This work quantifies both grounded and floating ice mass loss from approximately years 2000 through 2019. Ice mass loss in Greenland is 290 Gt yr^{-1} which is ~40 % larger than the 210 Gt yr^{-1} grounded ice mass loss estimates that neglect terminus retreat of ice at or near flotation citep:mankoff_2021. Ice mass loss in Antarctica is 280 Gt yr^{-1}.

#+BEGIN_SRC bash :exports none :results verbatim
cat ~/data/Mankoff_2021/708/MB_SMB_D_BMB_ann.csv \
    | cut -d, -f1-2 \
    | sed -e '1,/^1999/d' \
    | sed  '/^2019/q' \
    | datamash -t, mean 1,2

#+END_SRC

#+RESULTS:
: 2009.5,-209.8370565

# GL: (290/210 %) - 100 = 38.095238095 # 210 from Mankoff 2021
# AQ: (280/150 %) - 100 = 86.666666667

This work also reports gross not net values for most properties, which leads to significantly higher estimates of freshwater volumes. Net frontal retreat of ice shelves in Antarctica is 60 Gt yr^{-1}, but we report six times that amount or 345 Gt yr^{-1} of frontal retreat offset by 285 Gt yr^{-1} of frontal advance. Total freshwater volume flow rate from Greenland is ~1000 Gt yr^{-1} or ~3x mass loss, and from Antarctica is ~3500 Gt yr^{-1}, or ~12x mass loss.

#+LATEX: \end{abstract}
#+LATEX: \end{frontmatter}

* Introduction and Background

The flow of mass into, within, and out of ice sheets has global impacts including sea-level change, so Greenland and Antarctica's net mass balance have been the focus of a great deal of recent scientific research (citet:ipcc_AR6_ch9,otosaka_2023,mankoff_2021,rignot_2019, and many others). The mass loss from the grounded portion of the Greenlandic and Antarctic ice sheets contributes to sea level rise (SLR), and can be captured by a single value or time series per ice sheet. Reporting a single value is beneficial because it simplifies interpretation and comparison. However, ice sheets are complex systems and while their contribution to sea level rise is important, focusing on their SLR contribution alone neither provides a holistic view nor captures the general health and state of the ice sheet. As one example, an ice sheet that increases output via discharge or submarine melting by X % but has that offset by an equal increase in snowfall would report no net mass change or net SLR contribution, but has entered a different state when viewing constituent terms or gross values. Few studies consider all mass transport pathways and their relative magnitudes and uncertainties - this is typically limited to review papers, which may not focus on quantitative assessment of each process. 

Net mass flow or mass balance is typically analyzed using one or a combination of three methods.

The gravimetric method is observation-based and excels at measuring the grounded ice contribution to sea level rise, but cannot observe changes in floating ice, nor distinguish processes that contribute to changes of the grounded ice. Spatial resolution is O(100) km and temporal resolution is monthly (~30 day).

The volumetric method is also observation-based has spatial resolution of O(10) km and temporal resolution is ~10 day. It can be used over floating ice, and this is the primary method for observing ice shelf thinning from which basal melt is inferred. However, in Greenland the volumetric method has not been used to distinguish between surface and basal processes, and only reports total thinning.

The input-output (IO) method is a hybrid of regional climate models (RCM) and observation based (velocity, thickness). It is typically reported at low spatial resolution - at most individual glacier basin, but in theory can be applied at the resolution of the RCMs. Temporal resolution is ~10 days or whenever a new velocity map is generated. This method is the only one that captures all of the processes contributing to changes of grounded ice.

Here we use a combination of the IO and altimetry method. The IO is the primary source and the only source in Greenland, but altimetry provides ice shelf mass loss in Antarctica.

Although this information could be presented in a tabular display, graphical displays can have increased information density and provide insights not available in a table. Therefore, we present Sankey diagrams that provide an overview of all mass flow terms and processes for both the Greenlandic and Antarctic ice sheets.


** Introduction to Sankey diagrams

Sankey diagrams are graphical representations of flow or movement of any property (e.g., mass, energy, money, etc.). An early and famous use was Charles Minard's Map of Napoleon's Russian Campaign of 1812 (c.f., citet:kraak_2021) that combines the magnitude of active soldiers overlaid on a geographical map to show attrition during one battle in a war. The method was later refined, popularized, and eventually named after Captain Matthew Henry Phineas Riall Sankey who used it to show, among other things, the energy efficiency of a steam engine.

A similar display to the diagrams presented here by citet:cogley_2011 (Fig. 2) shows flows overlaid an a glacier schematic and here we build on that work by adding magnitude of processes and making the graphics proportional to magnitudes.

* Methods

# We use the data introduced above to derive some new values, some new estimates of mass flows not previously reported, and some adjustments to the above products.

We primarily use existing published values, and from these we derive only one new value from the sum of all other inputs minus outputs which we term net mass loss if negative or accumulation if positive. The existing values are valid over varying time periods. The majority of estimates are from 2000 through 2019. All mass flow terms, values for each flow, time span of each value, and reference publication are shown in Tables \ref{tab:gl} and \ref{tab:aq}.

We use constituent terms (i.e., gross not net) of surface mass balance from the Modèle Atmosphérique Régional (MAR) RCM for both Greenland citep:fettweis_2020 and Antarctica citep:agosta_2013 (XAVIER, WHAT REF SHOULD I USE?). The remaining products are hemisphere-specific.

In Greenland, we use ice discharge across flux gates ~5 km upstream from the grounding lines citep:mankoff_2021, frontal retreat citep:greene_2024, and basal mass loss citep:karlsson_2021.

In Antarctica we use ice discharge across grounding lines including both into ice shelf and non-shelf regions citep:rignot_2019, ice shelf basal melting  and calving citep:davison_2023, frontal retreat citep:greene_2022, and grounded ice basal mass loss citep:van-liefferinge_2013.

** Derived values

The derived value is only net mass change - here shown as `mass loss' except East Antarctica where it is `accumulation'. This term balances all the other terms, so that the Sankey diagram has outputs balancing inputs.

** New estimates

The Greenlandic ice discharge term citep:mankoff_2020_solid is across flux gates ~5 km upstream from the terminus. That discharge term is approximately correct at the flux gates, but is known to overestimate discharge across the grounding line because it neglects SMB losses between the flux gate and grounding line. These losses are estimated at ~17 Gt yr^{-1} by citet:kochtitzky_2023 who uses flux gates closer than the citet:mankoff_2020_solid flux gates. To account for this increased melt due to more distant flux gates we increase the citet:kochtitzky_2023 estimates to 25 Gt yr^{-1} and reduce discharge by this amount. How that discharge is separated into submarine melt or calving is highly uncertain and has not been quantified for all of Greenland. We estimate a 50 % \pm 40 % split between calving and submarine melt from citep:enderlin_2013.

There are no published values for Antarctic ice shelf grounding line retreat in units of Gt yr^{-1}, but we have an estimate of ~50 Gt yr^{-1} for the Amundsen Sea sector from B. Davison (personal comms.). We therefore assign 50 Gt yr^{-1} for West Antarctica, and 5 Gt yr^{-1} for both East Antarctica and the Antarctic Peninsula. <-- This needs improvement, but I'm not sure what else to do here.

In Greenland, there is no known assessment of grounding line retreat separate from ice front retreat, in units of Gt yr^{-1}. These two terms are the same in most places in Greenland, because there are few ice shelves. For Greenlandic frontal retreat we use published values from citet:kochtitzky_2023. We then use published values of Petermann glacier grounding line retreat (units m) from citet:millan_2022, ice velocity from citet:millan_2022, ice thickness from citet:ciraci_2023, and ice density of 917 kg m^{3} to calculate grounding line retreat in units of Gt yr^{-1}. We estimate ~1.5 Gt yr^{-1}.

** Other

Unlike typical reports of MAR values where sublimation is net sublimation, here sublimation is only the process that converts solid ice to a gas. The opposite is deposition. Evaporation and condensation are analogous but for liquid rather than gas.

In Antarctica, we use the MEaSUREs Antarctic Boundaries for IPY 2007-2009 from Satellite Radar, Version 2 (NSIDC product 0709; citet:mouginot_2017,rignot_2013) to separate Antarctica into East, West, and Peninsula.

** Sankey diagrams

The Sankey diagrams shown here are generated from a script that combines a CSV file of values with a \LaTeX\enspace template that uses the TikZ Sankey package citep:sankey. This architecture makes it trivial to generate similar diagrams for other time periods, differences between time periods, other regions, etc. We demonstrate this by separating Antarctic values into sub-regions (East, West, Peninsula), generating three new CSV files, and showing mass flows for these sub-regions in Appendix A.

*** Interpretation of graphics

Sankey diagrams are generally intuitive, but the following section may still be helpful in interpreting the diagrams shown here. The widths of all lines are proportional to all other widths, both within and among figures. Color here represents both phase and net mass change. Colors gray, blue, and yellow represent solid, liquid, and gaseous phases respectively, while red interior represents net mass loss. The latter may be counter-intuitive - for example to see mass loss as an input at the left (red in Fig. \ref{fig:gl}) even though most mass loss terms (runoff, calving, etc.) are at the right. This is because Sankey diagrams are balanced, here outputs are larger than inputs (hence net mass loss), and so the mass loss term is an input. This input is the drawdown of the historical `stable' ice mass.

These diagrams also do not represent every process perfectly. For example, frontal retreat is a combination of calving and submarine melting (and should therefore divide between ice and liquid with the same 50 % \pm 40 % uncertainty citep:enderlin_2013), but frontal retreat is shown separately here because it is usually treated separately in the literature.

We highlight frontal retreat and grounding line retreat both with a red outline, and by not including frontal retreat in the larger (in Greenland) discharge and submarine melting flow. We do this for two reasons.

First frontal retreat and grounding line retreat imply an imbalance. Regardless whether a system is gaining mass, losing mass, or in steady state. If there is long-term grounding line and frontal retreat, it implies a system imbalance even if not a numerical imbalance as represented here.

Secondly, these two terms are rarely included in mass change estimates. The gravimetric method does not see these processes, the volumetric method in Greenland is usually cropped at the some fixed grounding line upstream of these processes, and the IO method has typically ignored these two terms as downstream of the flux gates. This may be because grounding line retreat is difficult to observe and has not been quantified on an ice-sheet scale, and frontal retreat has only recently been estimated in Greenland citep:kochtitzky_2023,greene_2024 and Antarctica citep:greene_2022.

* Results
** Greenland

# #+CAPTION:Sankey mass flow diagrams for Greenland. All widths are proportional within and between images. Because Sankey diagrams balance all inputs and outputs, mass losses require a `drawdown' input (red) to balance the larger outputs.
# #+NAME: fig:gl
# [[./gl_baseline.pdf]]

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{gl_baseline.pdf}}
\caption{Sankey mass flow diagram for Greenland. All widths are proportional within and between images. Gray is ice, blue is liquid, and yellow is gaseous phase. Inputs (left, arrow tail) are balanced by outputs (right, arrow head). Because Sankey diagrams balance all inputs and outputs, mass losses require a `mass loss' input (red) to balance the larger outputs.}
\label{fig:gl}
\end{figure*}

The reported mass loss for Greenland is 290 Gt yr^{-1}, which is ~40 % higher than the 210 Gt yr^{-1} previously reported values from IO limited to grounded ice citep:mankoff_2021. Here two additional loss terms, frontal retreat and grounding line retreat, sum to 55 Gt yr^{-1}. When these are removed, values match the earlier grounded ice mass loss estimates within 25 Gt yr^{-1}, which is within the uncertainty.

** Antarctica

# #+CAPTION:Sankey mass flow diagrams for Antarctica. All widths are proportional within and between images. Because Sankey diagrams balance all inputs and outputs, mass losses require a `drawdown' input (red) to balance the larger outputs.
# #+NAME: fig:aq
# [[./aq_baseline.pdf]]

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{aq_baseline.pdf}}
\caption{Sankey mass flow diagrams for Antarctica. See Fig. \ref{fig:gl} for legend and details.}
\label{fig:aq}
\end{figure*}

The reported mass loss for Antarctica is 280. This is higher than most other estimates reported for Antarctica due to the inclusion of more terms - not just grounded ice mass loss and discharge or submarine melt and calving, but also frontal retreat.

# As previously stated, few existing studies outside of review papers address all terms, and the review papers usually do not focus on quantitative assessment of magnitude. Therefore, we compare parts of this graphic to other existing estimates.

# The ice sheet mass balance intercomparison experiment (IMBIE; citet:otosaka_2023) reports recent Greenlandic ice sheet mass loss as -257 \pm42 Gt yr^{-1}. Elsewhere the gravimetric method reports recent Greenlandic mass loss of ~277 Gt yr^{-1} (GRACE site, need CITATION). These are both significantly less than our estimate of 325 drawdown in order to balance the inputs with outputs. This can be directly attributable to the gravimetric method not observing frontal retreat (50 Gt yr^{-1}) nor grounding line retreat (5 Gt yr^{-1}). When these loss terms are removed from our estimate, it becomes 270 Gt yr^{-1} which is well within the uncertainty.

# \begin{figure*}
# \centering{\includegraphics[width=0.85\textwidth]{fig_aq_gl.png}}
# \caption{Sankey mass flow diagrams for Antarctica and Greenland, and Antarctica split into East, West, and Peninsula. All widths are proportional within and between images. Because Sankey diagrams balance all inputs and outputs, mass losses require a `drawdown' input (red) to balance the larger outputs, and mass gains requires an `accumulation' output (black) to balance the larger inputs.}
# \label{fig}
# \end{figure*}

* Discussion

** Missing terms, limitations, and simplifications

\label{sec:limits}

These figures neglect some mass flow processes (some of which are included in citet:cogley_2011 (Fig. 2), and simplify others.

+ Neglected processes include grounded ice basal freeze-on (c.f., citet:bell_2014). Basal melting estimates currently assume all melt leaves the ice sheet and is therefore mass loss. That seems unlikely, given both observations of freeze-on citep:bell_2014 and that some melt, especially from the geothermal term (c.f., citet:karlsson_2021) occurs under thick ice far inland and far from active subglacial conduits.

+ Sub-aqueous frontal melt is excluded in Antarctica, because it is usually excluded in the literature that focus on ice shelf basal melt or calving. We assume this term is included in the citet:davison_2023 calving estimates (IS IT??), but attributed to basal melt or calving rather than frontal melt. This process remains unquantified on ice-sheet wide scales.

+ Subaerial frontal melt and sublimation or the vertical face in above the water line citep:cogley_2011 (Fig. 2) is not explicitly treated but is included in other terms.

+ Grounding line retreat in both Greenland and Antarctica is largely unquantified in the units needed to include it here.

+ We neglect avalanche on and off ice sheets - these likely matter more for mountain glaciers.

+ Snow drift on and off is also excluded. There is likely little snow drift onto either ice sheet, but drifting off may be of similar magnitude to some of the other smaller terms shown here. Some drift off may be implicitly included in the sublimation term (TODO: Xavier?).

# + There may be other as-yet unidentified missing terms. For example, the earlier version of this graphic by \citet[Fig. 2]{cogley_2011} did not contain frontal nor grounding line retreat. These are two distinct processes when ice shelves exist, but can be treated as synonyms for one process at tidewater glacier margins. These terms were not only not included in citet:cogley_2011, but their respective values were highly uncertain, and still are, although recent work by citet:kochtitzky_2023,greene_2024 have constrained these values in Greenland. 

There are a variety of simplifications. For example, rainfall input does not all turn to ice as depicted by the arrows in these diagrams. Some enters as part of the refreezing loop, and some remains liquid and leaves as runoff or evaporation. Similarly, the evaporation output could pull from the refreezing loop (in the liquid phase, depicted by the blue color) and also directly from rainfall as stated above. Although some path details are simplified, the magnitudes are still correct. We also note the rainfall term is relatively small, and the issues raised here are likely an even smaller subset of the total rainfall. <-- Chad requests hard numbers to avoid wishy-washy, vague, and abstract. I don't have any hard numbers for this.

** Uncertainty

NOTE: I think uncertainty should be a big part of this paper, but maybe not. Maybe just a brief mention and column in the table? I'm struggling with this section, and have no idea of an in-depth example of my 2020 paper is useful or not. Probably not.

\vspace{1cm}

Here we discuss both the uncertainty of each term, and discuss the where this uncertainty comes from.

Sankey diagrams do not typically include a display of uncertainty, although it is possible to add a visual indicator to the graphic citep:vosough_2019. Here we do not include a display of uncertainty in the main graphics, but do in the tabular display (Tables \ref{tab:gl} and \ref{tab:aq}) and visually in Appendix C for Greenland.

*** General

# Here we report a single value from mostly overlapping time periods. However, changes in ice shelf melt rate or upstream glacier thinning occurred during these times citep:paolo_2023. As such, a time series line-plot or Sankey-per-year may be more appropriate to show

# We drop all unattached islands, so the sum of the regional terms may not equal the total Antarctic values in Fig. \ref{fig:aq_regions}.

All values are rounded to the nearest 5 Gt yr^{-1}, except values greater than zero and < 5 Gt yr^{-1} which are rounded up to 5 Gt yr^{-1}.

*** Magnitudes

Reported uncertainties are often \leq 15 %. Exceptions in Antarctica include ice shelf submarine melting and freeze-on with uncertainty of 300 % and 150 % respectively citep:paolo_2023, and grounded ice basal melting of 30 % uncertainty citep:van-liefferinge_2013. Exceptions in Greenland include grounded ice basal melting of 20 % citep:karlsson_2021, and the division of discharge when it is divided into submarine melt and calving, each of which have an uncertainty \pm 40 % based on citet:enderlin_2013. However, here the sum of these two terms is reasonably well constrained at ~10 % citep:mankoff_2020_solid, it is only the separation and form or phase (solid or liquid) that is highly uncertain.

*** Sources of uncertainty

The diverse source of inputs and outputs here have a range of reasons for their respective uncertainties. The errors here are often a combination of several of the sources of uncertainty. These include, but are not limited to,

+ Model limitations - Unknown physics, temporal or spatial resolution, or initial and boundary conditions.
+ Observational limits - Processes that are difficult to observe, or processes that are easy to observe or constraints on spatial resolution (e.g., number of sensors) or temporal resolution (e.g., satellite repeat period).
+ Researcher decisions - Researchers make mistakes, make intentional decisions in to save time, cost, complexity, etc. in their workflows.

Nonetheless, the broad agreement among the three mostly-independent methods of estimating the total mass loss (c.f., citet:otosaka_2023) suggests that even with all these sources of uncertainty, the mean values are reasonably well constrained and there is likely a randomness that cancels out when combining terms, as opposed to a bias that amplifies.

A specific example of multiple components of uncertainty that combines all of the above is the Greenlandic discharge term from citet:mankoff_2021. That is not explicitly displayed here, but it's value is ~475 \pm 50 Gt yr^{-1} prior to the downstream SMB correction, and after this correction submarine melting and calving are defined here as 50 % each of discharge. The primary source of discharge uncertainty is ice thickness at the location of the flux gates, which has large uncertainty near the grounding line of fast flowing glaciers. The ice thickness uncertainty is in turn due to a combination of observational (radar) and model (kriging).

# Observationally, radar is unable to see the bed when there is a large amount of water and nearby steep fjord sidewalls, and drilling a sufficient number of boreholes is prohibitive due to both cost and safety issues.

# Model limitations are inherent in the mass balance solution and kriging.

The discharge in citet:mankoff_2021 comes from the citet:mankoff_2020_solid product, where they use some velocity at 12 day temporal resolution, but that product although updated every 12 days comes from a 24 day average, which means minima and maxima are missed citep:greene_2020, although total displacement is captured.

Firn is excluded, which may be a reasonable choice for flux gates at low elevations when thickness was measured during the summer over a bare ice surface. Firn is regularly addressed in Antarctic products that consider ice density, but neither citet:mankoff_2020_solid nor any other ice density estimate that we know of treats crevasses, which may reduced ice volume by 20 % or more regionally citep:mankoff_2020_A380.

Finally, citet:mankoff_2020_solid intentionally excluded SMB effects downstream of the flux gate, although we apply a correction here to avoid double-counting that mass loss. The estimates used here from citet:kochtitzky_2023 did not exist at the time citet:mankoff_2020_solid was produced. Adjusting downstream SMB also requires addressing frontal retreat, which is itself a significant effort and had not yet been done (c.f., citep:kochtitzky_2023,greene_2024). Finally, MAR reports a 15 % uncertainty, but that is for an ice-sheet wide mean value. It seems likely MAR uncertainty is larger at the margins where there is significant summer melt, crevasses, and high topographic relief.

Each product here likely has a similar but different combination of reasons for their uncertainty including model, observation, and human caused.

Ice shelf net basal melt rates from citet:paolo_2023 for 2000 through 2017 are 980 (from gross terms of 1335 melt minus 355 freeze-on), 315 (515-200), 520 (665-145), and 145 (155-10) Gt yr^{-1} for all of Antarctica, East, West, and Peninsula regions respectively. Comparing these to citet:davison_2023 who only provide net, their estimates for 1997 through 2021 are 900, 390, 410, and 100 Gt yr^{-1} for the same regions, or ~8 % less (all Antarctica), 25 % more (East), 20 % less (West) and 30 % less (Peninsula).

# 100 - 900/980 % = 8.1632653061
# 100 - 390/315 % = -23.80952381    315*1.25 = 393.75
# 100 - 410/520 % = 21.1538461538
# 100 - 100/145 % = 31.0344827586

Temporal smoothing adds another source of error, that is similar to information lost by reporting net not gross. For example, if frontal advance and retreat are reported as zero on an annual scale, but have large sub-annual variability, the negative term (retreat) is a freshwater source that is lost in the annual value. The same holds true for non-zero reporting on a monthly scale that ignores sub-monthly variability.

# Advice from Hester: Synthesize what each of the uncertainties is a function of (lack of measurements/scale/timing of measurements/lack of process understanding/variability/etc.). Also, rather than singling the uncertainty of each factor the feedbacks between them could be indicated.

# %% Mass change of shelves is a bulk aggregate property, and should not the default reporting metric because it obscures information. For example, in theory ice shelf mass can grow even as they collapse, as long as the grounding line retreats (adds mass to the shelf from the upstream ice sheet) faster than the mass loss at the frontal or submarine boundaries. A mass flow diagram dedicated to ice shelves (this one is not) would clearly convey each of these processes. 

# %% \subsection{Drifting snow}

# %% %% From Hester: I think if you were to go into a discussion of snowdrift it should go further than, for example, the works of Lenaerts et al. Perhaps it is beter to plainly list the uncertainties / poor definitions but in terms of process just refer to the existing papers. However, I am in two minds about this.


** Constituent terms and net versus gross

We recommend the community report constituent terms, or gross not net. If needed, it is relatively straightforward to include a net term in addition to the constituent terms. There are numerous advantages.

More information is better. The potential benefits for future researchers to address currently-unknown research questions or undefined needs is likely to outweigh the costs of increased complexity, time, storage, and access.

Sea level rise research often focuses on how and why, not only how much. This is the reason that the IO method is used in addition to the gravimetric method, or why the gravimetric method reports seasonal and not only annual values - the larger amplitude seasonal signal informs us that there is increased winter mass gain over time, offset by even larger increases in summer mass loss.

However, even the IO method, usually estimated with a single SMB value rather than  constituent terms as shown here, may miss important information. For example, if net SMB remains constant over time, but snowfall and runoff both increase, this indicates a different ice sheet state, and this information should not be removed through reporting of net values.

Here for example we have shown that freshwater flux from one source, ice shelf frontal retreat in Antarctica, is six times larger than the net value, due to significant frontal retreat and advance.

Finally, although we argue for gross not net and inclusion of constituent terms in general when sharing outputs, we caution that any users should consider if this is the correct treatment for inputs. For any given term - basal freeze-on being a likely candidate for freshwater studies - it may be more correct to use net not gross.

* Conclusion

We show Sankey diagrams as an intuitive display for mass flow of ice sheet processes. A script supports generating these diagrams based on a CSV table, supporting bulk or automated processing for other ice sheets, sub-regions (e.g. East Antarctica or just one ice shelf), or other time periods or time spans.

By tracking all mass flow terms including floating ice we estimate total ice mass loss from ~2000 through ~2019 at 290 Gt yr^{-1} in Greenland and 280 Gt yr^{-1} in Antarctica.

* References                                              :ignore:

\bibliography{library}
\bibliographystyle{igs}

* Author contributions

#+NAME: tab:credit
#+BEGIN_SRC jupyter-python :exports results
import pandas as pd
df = pd.read_csv('credit.csv', skiprows=1)
df['Initials'] = [_[0] for _ in df['First']]
df['Initials'] += [_[0] if _ != 'foo' else '' for _ in df['Middle'].fillna('foo')]
df['Initials'] += [_[0] for _ in df['Last']]
df = df.drop(columns=['First','Middle','Last','Affiliation1','Affiliation2','ORCID'])
df = df.set_index('Initials').T

s = df.sum()
df = df[s.sort_values(ascending=False).index]

df.T
#+END_SRC

#+CAPTION: Author contributions following the CRediT system citep:allen_2019,brand_2015,allen_2014
#+RESULTS: tab:credit
| Initials | Data | Graphics | Wrote | Edited | Discussed |
|----------+------+----------+-------+--------+-----------|
| KDM      |    1 |        1 |     1 |      1 |         1 |

See https://drive.google.com/drive/folders/1g9vXuQofIL5MgtrtQ2zzlLiu69j1kTvJ?usp=sharing


* Conflict of Interest

No authors have any conflict of interest with the work presented here.

* Acknowledgments

We thank Damien Ringeisen for conversations in the development of this work.

# Also had brief discussions with: Katie Leonard, Jan Lenaerts, Robert Fausto, Andreas Ahlstrøm, 

We thank citep:sankey for the \LaTeX TikZ Sankey package, and citet:cogley_2011 for a reference graphic. Analysis was aided by the software packages Pandas (citet:pandas_team), Xarray (citet:xarray), and GRASS GIS (citet:GRASS), among other tools.

# , Xavier Fettweis, Benjamin Davison, Anna Hogg, Chad Greene, Katie Leonard, Jan Lenaerts, Damien Ringeisen, Liam Colgan, Robert Fausto, Dominik Fahrner, Nanna Karlsson, Brice Van Liefferinge, and Andreas Ahlstrøm for conversations in the development of this work.


* Appendix                                                :ignore:

\appendix
\section{Appendix A: Antarctic mass flow by region}
\label{appendix:aq_regions}

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{aq_east.pdf}}
\centering{\includegraphics[width=0.85\textwidth]{aq_west.pdf}}
\centering{\includegraphics[width=0.85\textwidth]{aq_peninsula.pdf}}
\caption{Sankey mass flow diagrams for Antarctica regions. East (top), West (middle), and Peninsula (bottom). All widths are proportional within and between images. En East Antarctica mass gain is an output at the bottom that balances the diagram, because without it, there are more flows into the system than out of it.}
\label{fig:aq_regions}
\end{figure*}

\clearpage
\section{Appendix B: Tables of values}
\label{appendix:B}

+ Should tables be sorted by magnitude? By input-then-output? By process (SMB, etc.)?

+ Will Kochtitzky: I took uncertainty as 4 % because you report "481.8 ± 24.0 for 2000–2010 and 510.2 ± 18.6 Gt a−1 for 2010–2020." from which I'm estimating a) 20/500 % = 4 % and b) an annual rate of 50 Gt/yr. Is this correct?

+ TODO: Antarctic frontal advance and retreat uncertainty from Greene abstract: 5,874 ± 396. Need to recompute from data.

# #+NAME: tab:gl
# | Term                   | Value |    Period | Source                | Comment                     |
# |------------------------+-------+-----------+-----------------------+-----------------------------|
# | Rainfall               |    45 | 2000-2019 | citet:fettweis_2020   |                             |
# | Condensation           |     5 | 2000-2019 | citet:fettweis_2020   |                             |
# | Deposition             |    10 | 2000-2019 | citet:fettweis_2020   |                             |
# | Snowfall               |   685 | 2000-2019 | citet:fettweis_2019   |                             |
# | Refreezing             |   195 | 2000-2019 | citet:fettweis_2020   | RFZ = ME + RF - RU          |
# | Evaporation            |    10 | 2000-2019 | citet:fettweis_2020   |                             |
# | Runoff                 |   440 | 2000-2019 | citet:fettweis_2020   |                             |
# | Basal melting          |    20 |    steady | citet:karlsson_2020   |                             |
# | Discharge              |   490 | 2000-2019 | citet:mankoff_2020    | Submarine melting + calving |
# | Submarine melting      |   245 |           | citet:enderlin_2013   | 50 % of discharge           |
# | Freeze-on              |     0 |           |                       | None in Greenland           |
# | Calving                |   245 |           | citet:enderlin_2013   | 50 % of discharge           |
# | Grounding line retreat |     5 |           |                       | Estimate                    |
# | Frontal retreat        |    50 | 2000-2020 | citet:kochtitzky_2023 |                             |
# | Frontal advance        |     0 |           |                       | None in GL                  |
# | Sublimation            |    60 | 2000-2019 | citet:fettweis_2020   |                             |
# | Mass loss or gain      |       |           | Derived               |                             |
# #+CAPTION: Greenland mass flow terms, values, and metadata

# #+NAME: tab:aq
# | Term                   |                    Value |               Period | Source                                          | Comment     |
# |------------------------+--------------------------+----------------------+-------------------------------------------------+-------------|
# | Rainfall               |                        5 |            2000-2019 | citet:fettweis_2020                             |             |
# | Condensation           |                        5 |            2000-2019 | citet:fettweis_2020                             |             |
# | Deposition             |                       75 |            2000-2019 | citet:fettweis_2020                             |             |
# | Snowfall               |                     2750 |            2000-2019 | citet:fettweis_2020                             |             |
# | Refreezing             |                      105 |            2000-2019 | citet:fettweis_2020                             |             |
# | Evaporation            |                        5 |            2000-2019 | citet:fettweis_2020                             |             |
# | Runoff                 |                       10 |            2000-2019 | citet:fettweis_2020                             |             |
# | Basal melting          |                       70 |                      | citet:van-liefferinge_2013                      |             |
# | Discharge              | 1335+1350+(2275-75-1840) | 1997-2021; 1999-2017 | Sum of SUB + ICE                                | See caption |
# | Submarine melting      |                     1335 |            2000-2017 | citet:paolo_2023                                |             |
# | Freeze-on              |                      355 |            2000-2017 | citet:paolo_2023                                |             |
# | Calving                |      1350+(2275-75-1840) | 1997-2021; 1999-2017 | citet:davison_2023 + citet:rignot_2019 grounded | See caption |
# | Grounding line retreat |                       50 |            1997-2021 | Davison (personal comm.)                        |             |
# | Frontal retreat        |             79+122+145-1 |            2000-2021 | citet:greene_2022                               |             |
# | Frontal advance        |                181+1+103 |            2000-2021 | citet:greene_2022                               |             |
# | Sublimation            |                      230 |            2000-2019 | citet:fettweis_2020                             |             |
# | Mass loss or gain      |                          |                      | Derived                                         |             |
# #+CAPTION: Antarctic mass flow terms, values, and metadata. Calving represents ice shelf calving (1350 Gt yr^{-1} from citet:davison_2023) plus 435 Gt yr^{-1} which is the difference between 2275 Gt yr^{-1} discharge across all sectors 1999 through 2017 from citet:rignot_2019 and 1840 Gt yr^{-1} ice shelf grounding line discharge from citet:davison_2023 - that is, 435 Gt yr^{-1} is estimated as calving from non-shelf sectors. Grounding line retreat here is largely unknown. We estimate \(\sim\)50 Gt yr^{-1} in the Amundsen sea sector (Davison, personal communication).

#+BEGIN_latex
\begin{table*}[htbp]
\caption{Greenland mass flow terms, values [Gt yr\textsuperscript{-1}], Uncertainty [\%], and metadata. Discharge is computed as solid ice discharge from \cite{mankoff_2020_solid} ~5 km upstream of the grounding line minus a below-flux-gate surface melting (SMB correction) based on \cite{kochtitzky_2023}. Grounding line retreat estimate from Methods section is poorly constrained in Greenland.}
\label{tab:gl}
\centering
\begin{tabular}{lrrrll}
Term & Value & Unc. & Period & Source & Comment\\
\hline
Rainfall & 45 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Condensation & 5 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Deposition & 10 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Snowfall & 685 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Refreezing & 195 & 15 & 2000-2019 & \cite{fettweis_2020} & Melt + rainfall - runoff\\
Evaporation & 10 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Runoff & 440 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Basal melting & 20 & 20 & & \cite{karlsson_2021} & \\
Discharge & 450 & 10 & 2000-2019 & Discharge minus below-gate SMB & See caption\\
Calving & 225 & 40 & & \cite{enderlin_2013} & 50 \% of discharge\\
Submarine melting & 225 & 40 &  & \cite{enderlin_2013} & 50 \% of discharge\\
Freeze-on & 0 & &  &  & None in Greenland\\
Grounding line retreat & 5 & ? & &  & See caption\\
Frontal retreat & 50 & 4 & 2000-2020 & \cite{kochtitzky_2023} & \\
Frontal advance & 0 & & &  & None in Greenland\\
Sublimation & 60 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Mass loss or gain & & & & Derived from abs(sum(in)-sum(out)) &\\
\end{tabular}
\end{table*}

\begin{table*}[htbp]
\caption{Antarctic mass flow terms, values [Gt yr\textsuperscript{-1}], Uncertainty [\%], metadata. Calving represents ice shelf calving (1350 Gt yr\textsuperscript{-1} from \cite{davison_2023} plus 435 Gt yr\textsuperscript{-1} which is the difference between 2200 Gt yr\textsuperscript{-1} \textpm{}6 \% discharge across all sectors 1999 through 2017 from \cite{rignot_2019} and 1840 Gt yr\textsuperscript{-1} \textpm{}10 \% ice shelf grounding line discharge from \cite{davison_2023} - that is, 435 Gt yr\textsuperscript{-1} is estimated as calving from non-shelf sectors. Grounding line retreat here is largely unknown. We estimate \(\sim\)50 Gt yr\textsuperscript{-1} in the Amundsen sea sector (Davison, personal communication)}
\label{tab:aq}
\centering
\begin{tabular}{lrrrll}
Term & Value & Unc. & Period & Source & Comment\\
\hline
Rainfall & 5 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Condensation & 5 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Deposition & 75 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Snowfall & 2750 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Refreezing & 105 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Evaporation & 5 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Runoff & 10 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Basal melting & 70 & 30 & & \cite{van-liefferinge_2013} & \\
% Discharge & 1335+1350+(2200-1840) & & 1997-2021; 1999-2017 & Sum of submarine melting + calving & See caption\\
Submarine melting & 1335 & 300 & 2000-2017 & \cite{paolo_2023} & \\
Freeze-on & 355 & 150 & 2000-2017 & \cite{paolo_2023} & \\
Calving & 1350+(2200-1840) & 6; 10 & 1997-2021; 1999-2017 & See caption\\
Grounding line retreat & 50 & ? & 1997-2021 & Davison (personal comm.) & \\
Frontal retreat & 345 & 7 & 2000-2021 & \cite{greene_2022} & \\
Frontal advance & 285 & 7 & 2000-2021 & \cite{greene_2022} & \\
Sublimation & 230 & 15 & 2000-2019 & \cite{fettweis_2020} & \\
Mass loss or gain & & & & Derived from abs(sum(in)-sum(out)) & \\
\end{tabular}
\end{table*}
#+END_latex


\clearpage
\section{Appendix C: A lousy attempt at error display}

Perhaps Sankey diagrams are not good for uncertainty contrary to citet:vosough_2019. I've added some error bars. Maybe we just discuss in text and in tabular form?

\begin{figure*}
\centering{\includegraphics[width=0.85\textwidth]{gl_err.pdf}}
\caption{Error bars overlaid on a few terms for Greenland.}
\end{figure*}

* COMMENT Figures

Figure 1: The parts of engine that remained attached to the plane after the accident. Photo taken in-flight by passenger Enrique Guillen.

Figure 2: Overview of field site. Fan hub fragment found to left of T1 label. T2A and T2B dots were secondary targets. Orange dots near T1 are locations of snow-covered crevasses from ground-penetrating radar (GPR) survey to T1. Airplane icon shows accident location on solid black line flight path. Dots in upper right show initial debris field. White and black dashed lines are primary and secondary search areas, respectively. Pale colored lines show GPR tracks from C4 wide-area search (right-most circles indicate C4 basecamp). C5 basecamp marked with tent icon. Bottom left shows white Greenland with circle representing the approximate location. Basemap is a contrast-enhanced Landsat image (15 m per pixel) and curved features in lower right corner are the surface depression over snow-covered crevasses.

Figure 3: Overview of field site search area and crevasse fields. Similar to Fig. 2 except zoomed in and here basemap is an ultra-high frequency (UHF) synthetic aperture radar image from the SETHI instrument acquired during the third campaign. Approximate crevass locations are shown by light-colored streaks. Fan hub fragment location marked with X near T1. MEaSUREs 2015 - 2017 average velocity shown by arrows, with minimum 20 m yr^{-1} and maximum 75 m yr^{-1} marked at top left and bottom right, respectively.

Figure 4: Density profile from April 2018 (C4). Snow pit down to 1.5 m and then nearby core from 1.5 to 12 m. Blue lines denote visible ice layers.

Figure 5: A SnowTEM photograph (top) and down-looking schematic (bottom). Snowmobile with instrumentation (left), transmitter coil (center) and receiver coil (right). Dual receiver in photo is experimental setup not used during search. Photo by Thue Bording.

Figure 6: Local view of Target 1 site. Basemap is 0.18 m/pixel resolution X-band composite, acquired during 2018 C3 but shifted so that target T1 lines up with location where fan hub fragment was found during 2019 C5. Dark spot near T1 arrow marks the fan hub fragment. Dark and light streaks mark crevasses, also detected during C5 FrostyBoy GPR survey and marked with orange. Black dashed line is approximate transect shown in Fig. 7. White lines and camera show approximate view and region of Fig. 9. Helicopter (credit: Rune Kraghede) added graphically at scale to show work environment (camera not to scale).

Figure 7: Anomalous feature (in white circle and zoomed in circle) and crevasses (white boxes) from 400 MHz SIR-30 GPR towed by FrostyBoy. Near top axis, dashed box shows planned pit and work island, and tent (not to scale) marks camp island (Figs. 6 and 9). On bottom axis, A and A’ refer to labels in Fig. 9. N and S refer to North and South ends of transect (see Fig. 6).

Figure 8: Plot of SnowTEM signal response showing signal strength (y-axis; \(d\)B is change in magnetic B-field, not decibel dB) v. time (x-axis). The open symbols have opposite polarity from the closed symbols. Squares show the maximum signal from the T1 target, Triangles show responses with no engine pieces, and circles show the signal from test piece. The first half (until 100 \(\mu\)s) of the no-engine piece signal is dominated by an internal instrument signal, and thereafter noise or couplings with opposite polarity. The three consecutive gates at 75, 100 and 132 \(\mu\)s were used for localisation of the test piece.

Figure 9: Photograph from helicopter of excavation work-site. A & A': Dark red graphic overlays between flags mark known crevasse locations as detected by GPR and DGNSS (also in Figs. 6 and 7). Dashed lines enclose safe areas and pink marks unsafe areas defined with GPR data, the UHF basemap (Fig. 3), extensive snow probing, and crevasse location uncertainty with distance from known crevasse locations. B: Ramp out of pit. C: Plywood used to cover pit overnight to prevent drifting snow filling. D: Safety rope bridging crevasse between the northern (far) camp island and the southern (near) work island. E: Sled. F: Winch and winch platform. G: Generator used to power winch. H: Bamboo poles marking polar bear alarm trip-wire surrounding sleep tent. I: Herman Nelson heater, hose, and fuel barrel. J: Helicopter landing zone. Photo by Austin Lines.

\clearpage

\begin{table*} % table2, two column
\caption{Overview of field campaigns. Campaign duration is days in Greenland. Camp duration refers to nights camping on-ice. Equipment weight is the weight of equipment moved to the ice sheet for the campaign. C4 combines helicopter and Twin Otter flights.}
\centering
\begin{tabular}{lllllll}
 &      & Time since   & Campaign  & Camp [days]      & Flights [days]      & Equipment \\
 & Date & event [days] & [days]    & planned/actual   & with/without delays & weight [kg] \\\hline
C1  & Oct '17      & 4-11     & 8   & 0/0    & 5/3   & \\
C2  & Mar '18      & 174-181  & 7   & 0/0    & 0/1   & \\
C3  & Apr '18      & 184-201  & 17  & 0/0    & 5/5   & \\
C4  & Apr/May '18  & 199-228  & 29  & 23/23  & 3/5   & 3000-4000\\
C5  & May '19      & 572-605  & 33  & 24/15  & 10/9  & 6,500\\
C6  & Jun/Jul '19  & 630-644  & 14  & 0/2    & 3/6   & 3000-4000\\
\end{tabular}
\end{table*}

* LaTeX Setup                                           :noexport:
#+NAME: jog-latex-setup
#+BEGIN_SRC elisp
(add-to-list 'org-latex-classes
               `("igs"
                 "\\documentclass{igs}
               [NO-DEFAULT-PACKAGES]
               [NO-PACKAGES]
               [EXTRA]"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )

(org-add-link-type
 "citet"  (lambda (key) (kdm/org-pdf-open key))
 (lambda (path desc format)
   (cond
    ((eq format 'latex) (format "\\cite{%s}" path))
    ((eq format 'ascii) (format "%s" desc))
    )))
(org-add-link-type
 "citep"  (lambda (key) (kdm/org-pdf-open key))
 (lambda (path desc format)
   (cond
    ((eq format 'latex) (format "\\citep{%s}" path))
    ((eq format 'ascii) (format "%s" desc))
    )))

(setq-local org-latex-title-command "")
#+END_SRC

#+RESULTS: jog-latex-setup

* TODO QC                                               :noexport:

(langtool-check)
(langtool-correct-buffer)
(langtool-check-done)

Export as ASCII, then,

#+BEGIN_SRC elisp :results none :eval no-export
(setq org-ascii-text-width 80)
(org-ascii-export-to-ascii)
#+END_SRC

#+BEGIN_SRC bash :cmdline "-i" :results output :eval no-export :exports none
this='ms.txt'
aspell list < $this | sort | uniq
echo "\n"

declare -a cmds=("style" "diction -s")
for cmd in "${cmds[@]}"; do
    echo "###\n### $cmd\n###"
    #echo $cmd $this
    ${cmd} ${this}
    echo "\n"
done
#+END_SRC

* LaTeXdiff                                             :noexport:
#+BEGIN_SRC sh :results verbatim :results none :eval no-export

OLD=A380_ce66c80.tex
NEW=A380.tex
latexdiff --disable-citation-markup --append-safecmd="textcite,autocite" --config="PICTUREENV=(?:picture|DIFnomarkup|tabular)[\w\d*@]*" $OLD $NEW > diff.tex

# NOTE: Stil requires some manual editing of diff.tex, particularly
# when \DIFDEL and \DIFADD are inside CITE commands.

# latexmk diff.tex
#+END_SRC
#+RESULTS:

* Release                                               :noexport:

#+BEGIN_SRC bash :exports none :results none
pandoc ms.org --bibliography library.bib --citeproc --csl ~/Documents/templates/copernicus-publications.csl -o ms.docx
# xdg-open ms.docx
#+END_SRC
